<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getServiceName</value>
  <array name="sig" type="value" depth="1">
    <value>[o] field:0:required folderName</value>
    <value>[o] field:0:required serviceName</value>
    <value>[o] field:0:required fullName</value>
    <value>[o] field:0:required successFlag</value>
    <value>[o] field:0:required errorMessage</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqDQogKiBTZXJ2aWNlIGlzIGRlc2lnbmVkIHRvIHJldHVybiB0aGUgY3VycmVudCBzZXJ2aWNl
IG5hbWUuIE91dHB1dDoNCiAqIGZvbGRlclBhdGggLSB0aGUgZm9sZGVyIHBhdGggdG8gdGhlIHNl
cnZpY2Ugc2VydmljZU5hbWUgLSB0aGUgc2VydmljZQ0KICogbmFtZSBmdWxsTmFtZSAtIHRoZSBm
b2xkZXIgcGF0aCArICI6IiArIHNlcnZpY2Ugc3VjY2Vzc0ZsYWcgLSB0cnVlIG9yDQogKiBmYWxz
ZSBlcnJvck1lc3NhZ2UgLSBlcnJvciBkZXRhaWwuIFRoaXMgaXMgc2V0IHRvICJOb25lIiBpZiBu
byBlcnJvcg0KICogb2NjdXJzLg0KICogDQogKiBOT1RFIDE6IEJlY2F1c2UgdGhpcyBzZXJ2aWNl
IHJlbGllcyBvbiBhIG1ldGhvZCBpbnZvY2F0aW9uIHRoYXQgcmV0cmlldmVzDQogKiB0aGUgTlNT
ZXJ2aWNlIG9iamVjdCByZWxhdGluZyB0byB0aGUgY2FsbGluZyBzZXJ2aWNlLCBpdCB3aWxsICpO
T1QqIHdvcmsNCiAqIGFzIGRlc2lyZWQgaWYgcnVuIGluZGVwZW5kZW50bHkuIEluc3RlYWQsIGl0
IHdpbGwgcmV0dXJuIGluZm9ybWF0aW9uIG9uDQogKiB0aGUgY3VycmVudCBzZXJ2aWNlICh0aGlz
IG9uZSkgYW5kIHNldCB0aGUgInN1Y2Nlc3NGbGFnIiBhbmQNCiAqICJlcnJvck1lc3NhZ2UiIHZh
bHVlcyB0byBpbmRpY2F0ZSBhbiBlcnJvci4gTk9URSAyOiBUaGlzIHNlcnZpY2UgdXNlcw0KICog
bm9uLXB1YmxpYyBBUElzIHdpdGhpbiB0aGUgd2ViTWV0aG9kcyBJbnRlZ3JhdGlvbiBTZXJ2ZXIu
IFRoZXNlIG1heQ0KICogY2hhbmdlIGluIGZ1dHVyZSByZWxlYXNlcyBvZiB0aGUgcHJvZHVjdCAq
d2l0aG91dCogbm90aWNlLiBUaGVzZSBtZXRob2QNCiAqIGludm9jYXRpb25zIGFyZSBtYXJrZWQg
YXMgc3VjaC4NCiAqIA0KICovDQoNCi8vIEluc3RhbnRpYXRlIGEgY3Vyc29yIGZvciBhY2Nlc3Mg
dG8gdGhlIHBpcGVsaW5lDQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvciA9IHBpcGVsaW5lLmdl
dEN1cnNvcigpOw0KDQovLyBXb3JraW5nICYgT3V0cHV0IFZhcmlhYmxlcyAtIENyZWF0ZSBhbGwg
b3V0cHV0ICYgd29ya2luZyB2YXJpYWJsZXMNCk5TU2VydmljZSBjYWxsaW5nU2VydmljZSA9IG51
bGw7DQpTdHJpbmdUb2tlbml6ZXIgc3RyVG9rID0gbnVsbDsNClN0cmluZyBmb2xkZXJQYXRoID0g
bmV3IFN0cmluZygpOw0KU3RyaW5nIHNlcnZpY2VOYW1lID0gbmV3IFN0cmluZygpOw0KU3RyaW5n
IGZ1bGxOYW1lID0gbmV3IFN0cmluZygpOw0KU3RyaW5nIHN1Y2Nlc3NGbGFnID0gInRydWUiOw0K
U3RyaW5nIGVycm9yTWVzc2FnZSA9ICJOb25lIjsNCg0KLy8gSW5wdXQgVmFyaWFibGVzDQovLyBO
b25lDQoNCi8vIFNlcnZpY2UgQm9keQ0KLy8gVGhpcyBwdWJsaWNseSBkb2N1bWVudGVkIG1ldGhv
ZCBnZXRzIHRoZSBOU1NlcnZpY2Ugb2JqZWN0IGFzc29jaWF0ZWQgd2l0aA0KLy8gdGhlIGNhbGxp
bmcgc2VydmljZS4NCmNhbGxpbmdTZXJ2aWNlID0gU2VydmljZS5nZXRDYWxsaW5nU2VydmljZSgp
Ow0KDQovKioNCiAqIElmIHRoZSBjYWxsaW5nU2VydmljZSBpcyBub3QgYXZhaWxhYmxlIChtZWFu
aW5nIHRoYXQgdGhlIHNlcnZpY2Ugd2FzIHJ1bg0KICogZGlyZWN0bHksIHNldCB0aGUgImNhbGxp
bmdTZXJ2aWNlIiB0byBob2xkIHRoZSB2YWx1ZXMgZm9yIHRoZSBjdXJyZW50DQogKiBzZXJ2aWNl
ICh0aGlzIG9uZSkuIEFkZGl0aW9uYWxseSwgc2V0IHRoZSAic3VjY2Vzc0ZsYWciIGFuZA0KICog
ImVycm9yTWVzc2FnZSIgZmllbGRzIHRvIGluZGljYXRlIGEgcHJvYmxlbS4NCiAqLw0KaWYgKGNh
bGxpbmdTZXJ2aWNlID09IG51bGwpDQp7DQogIGNhbGxpbmdTZXJ2aWNlID0gSW52b2tlU3RhdGUu
Z2V0Q3VycmVudFNlcnZpY2UoKTsNCiAgc3VjY2Vzc0ZsYWcgPSAiZmFsc2UiOw0KICBlcnJvck1l
c3NhZ2UgPSAiTm8gY2FsbGluZyBzZXJ2aWNlIGZvdW5kLi4uIFJldHVybmluZyBpbmZvcm1hdGlv
biBmb3IgdGhpcyBzZXJ2aWNlIGluc3RlYWQuIjsNCn0NCg0KLyoqDQogKiBOb24tcHVibGljIEFQ
SS4gSG93ZXZlciwgdGhpcyBjYWxsIGlzIHJlbGF0aXZlbHkgc2FmZSwgYXMgInRvU3RyaW5nIiBp
cyBhDQogKiBzdGFuZGFyZCBtZXRob2QgdGhhdCBpcyBub3JtYWxseSBvdmVycmlkZW4gZnJvbSB0
aGUgcm9vdA0KICogamF2YS5sYW5nLk9iamVjdC4NCiAqLw0KZnVsbE5hbWUgPSBjYWxsaW5nU2Vy
dmljZS50b1N0cmluZygpOw0KDQovKioNCiAqIFVzZSBTdHJpbmdUb2tlbml6ZXIsIGZyb20gdGhl
IGphdmEudXRpbCBwYWNrYWdlLCB0byBleHRyYWN0IHRoZQ0KICogZm9sZGVyUGF0aCBhbmQgc2Vy
dmljZU5hbWUgdmFsdWVzLg0KICovDQp0cnkNCnsNCiAgc3RyVG9rID0gbmV3IFN0cmluZ1Rva2Vu
aXplcihmdWxsTmFtZSwgIjoiKTsNCiAgZm9sZGVyUGF0aCA9IHN0clRvay5uZXh0VG9rZW4oKTsN
CiAgc2VydmljZU5hbWUgPSBzdHJUb2submV4dFRva2VuKCk7DQp9DQpjYXRjaCAoamF2YS5sYW5n
LkV4Y2VwdGlvbiBleCkNCnsNCiAgU3lzdGVtLm91dC5wcmludGxuKCJDUklUSUNBTCBFUlJPUjog
Q2hlY2sgdGhlIHRvU3RyaW5nKCkgbWV0aG9kIHdpdGhpbiBOU1NlcnZpY2UgdG8gZW5zdXJlIHRo
YXQgaXQgaXMgcmV0dXJuaW5nIEZvbGRlcjpTZXJ2aWNlTmFtZSBhcyBkZXNpcmVkLiIpOw0KICBz
dWNjZXNzRmxhZyA9ICJmYWxzZSI7DQogIGVycm9yTWVzc2FnZSA9ICJDUklUSUNBTCBFUlJPUjog
Q2hlY2sgdGhlIHRvU3RyaW5nKCkgbWV0aG9kIHdpdGhpbiBOU1NlcnZpY2UgdG8gZW5zdXJlIHRo
YXQgaXQgaXMgcmV0dXJuaW5nIEZvbGRlcjpTZXJ2aWNlTmFtZSBhcyBkZXNpcmVkLiI7DQoNCn0N
Cg0KLy8gUG9wdWxhdGUgc2VydmljZSBvdXRwdXQNCmlmIChwaXBlbGluZUN1cnNvci5maXJzdCgi
Zm9sZGVyUGF0aCIpKQ0KICBwaXBlbGluZUN1cnNvci5kZWxldGUoKTsNCnBpcGVsaW5lQ3Vyc29y
Lmluc2VydEFmdGVyKCJmb2xkZXJQYXRoIiwgZm9sZGVyUGF0aCk7DQoNCmlmIChwaXBlbGluZUN1
cnNvci5maXJzdCgic2VydmljZU5hbWUiKSkNCiAgcGlwZWxpbmVDdXJzb3IuZGVsZXRlKCk7DQpw
aXBlbGluZUN1cnNvci5pbnNlcnRBZnRlcigic2VydmljZU5hbWUiLCBzZXJ2aWNlTmFtZSk7DQoN
CmlmIChwaXBlbGluZUN1cnNvci5maXJzdCgiZnVsbE5hbWUiKSkNCiAgcGlwZWxpbmVDdXJzb3Iu
ZGVsZXRlKCk7DQpwaXBlbGluZUN1cnNvci5pbnNlcnRBZnRlcigiZnVsbE5hbWUiLCBmdWxsTmFt
ZSk7DQoNCmlmIChwaXBlbGluZUN1cnNvci5maXJzdCgic3VjY2Vzc0ZsYWciKSkNCiAgcGlwZWxp
bmVDdXJzb3IuZGVsZXRlKCk7DQpwaXBlbGluZUN1cnNvci5pbnNlcnRBZnRlcigic3VjY2Vzc0Zs
YWciLCBzdWNjZXNzRmxhZyk7DQoNCmlmIChwaXBlbGluZUN1cnNvci5maXJzdCgiZXJyb3JNZXNz
YWdlIikpDQogIHBpcGVsaW5lQ3Vyc29yLmRlbGV0ZSgpOw0KcGlwZWxpbmVDdXJzb3IuaW5zZXJ0
QWZ0ZXIoImVycm9yTWVzc2FnZSIsIGVycm9yTWVzc2FnZSk7DQo=</value>
</Values>
