<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">makeSystemCall</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required command</value>
    <value>[i] field:0:required synchronous {"true","false"}</value>
    <value>[o] field:0:required status</value>
    <value>[o] field:0:required output</value>
    <value>[o] field:0:required error</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">DQovLyBET1MgU3ludGF4OiBjbWQuZXhlIC9jICdjb21tYW5kJw0KLy8gRXhhbXBsZTogY21kLmV4
ZSAvYyBjb3B5IGxvZy50eHQgbG9nMi50eHQNCg0KSURhdGFDdXJzb3IgaWRjUGlwZWxpbmUgPSBw
aXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmluZyBzdHJPdXRwdXQgPSAiIjsNClN0cmluZyBzdHJF
cnJvciA9ICIiOw0KU3RyaW5nIHN0ckNvbW1hbmQgPSBudWxsOw0KaWYgKGlkY1BpcGVsaW5lLmZp
cnN0KCJjb21tYW5kIikpDQp7DQogIHN0ckNvbW1hbmQgPSAoU3RyaW5nKSBpZGNQaXBlbGluZS5n
ZXRWYWx1ZSgpOw0KfQ0KZWxzZQ0Kew0KICByZXR1cm47DQp9DQoNCi8vICoqKiBDaGVjayBpZiBj
b21tYW5kIGlzIG9uIHRoZSBhbGxvd2VkIGxpc3QgKioqDQpJRGF0YSBpbiA9IElEYXRhRmFjdG9y
eS5jcmVhdGUoKTsNCklEYXRhQ3Vyc29yIGlkY0luID0gaW4uZ2V0Q3Vyc29yKCk7DQppZGNJbi5p
bnNlcnRBZnRlcigicGFyYW1OYW1lIiwgImFsbG93ZWRDb21tYW5kcyIpOw0KaWRjSW4uaW5zZXJ0
QWZ0ZXIoInBhcmFtVmFsdWUiLCBzdHJDb21tYW5kKTsNCk5TTmFtZSBuc0NoZWNrU2VydmljZU5h
bWUgPSBOU05hbWUuY3JlYXRlKCJQU1V0aWxpdGllcy5jb25maWc6Y2hlY2tQYXJhbWV0ZXJWYWxp
ZGl0eSIpOw0KaWRjSW4uZGVzdHJveSgpOw0KSURhdGEgb3V0Ow0KdHJ5DQp7DQogIG91dCA9IFNl
cnZpY2UuZG9JbnZva2UobnNDaGVja1NlcnZpY2VOYW1lLCBpbik7DQp9DQpjYXRjaCAoRXhjZXB0
aW9uIGUpDQp7DQogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUpOw0KfQ0KSURhdGFDdXJz
b3IgaWRjT3V0ID0gb3V0LmdldEN1cnNvcigpOw0KU3RyaW5nIHN0clZhbGlkID0gbnVsbDsNCmlm
IChpZGNPdXQuZmlyc3QoInZhbGlkIikpDQp7DQogIHN0clZhbGlkID0gKFN0cmluZykgaWRjT3V0
LmdldFZhbHVlKCk7DQp9DQppZGNPdXQuZGVzdHJveSgpOw0KDQppZiAoc3RyVmFsaWQuZXF1YWxz
KCJmYWxzZSIpKQ0Kew0KICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiU3BlY2lmaWVkIGNv
bW1hbmQgaXMgbm90IG9uIHRoZSBhbGxvd2VkIGxpc3QgaW4gdGhlIFBTVXRpbGl0aWVzIGNvbmZp
Z3VyYXRpb24gZmlsZSEiKTsNCn0NCi8vICoqKiBFbmQgY2hlY2sgKioqDQoNCmlkY1BpcGVsaW5l
LmZpcnN0KCJzeW5jaHJvbm91cyIpOw0KU3RyaW5nIHN0clN5bmNocm9ub3VzID0gKFN0cmluZykg
aWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsNCg0KUHJvY2VzcyBwcm9jZXNzID0gbnVsbDsNCg0KdHJ5
DQp7DQogIHByb2Nlc3MgPSAoUnVudGltZS5nZXRSdW50aW1lKCkpLmV4ZWMoc3RyQ29tbWFuZCk7
DQoNCiAgaWYgKHN0clN5bmNocm9ub3VzLmVxdWFscygidHJ1ZSIpKQ0KICB7DQoNCiAgICAvLyBQ
cm92aWRlIGFuIG91dGxldCBmb3IgSU8gZm9yIHRoZSBwcm9jZXNzDQogICAgU3RyaW5nIGxpbmU7
DQogICAgQnVmZmVyZWRSZWFkZXIgaXIgPSBuZXcgQnVmZmVyZWRSZWFkZXIobmV3IElucHV0U3Ry
ZWFtUmVhZGVyKHByb2Nlc3MuZ2V0SW5wdXRTdHJlYW0oKSkpOw0KICAgIEJ1ZmZlcmVkUmVhZGVy
IGVyID0gbmV3IEJ1ZmZlcmVkUmVhZGVyKG5ldyBJbnB1dFN0cmVhbVJlYWRlcihwcm9jZXNzLmdl
dEVycm9yU3RyZWFtKCkpKTsNCiAgICB3aGlsZSAoKGxpbmUgPSBpci5yZWFkTGluZSgpKSAhPSBu
dWxsKQ0KICAgIHsNCiAgICAgIFN5c3RlbS5vdXQucHJpbnRsbihsaW5lKTsNCiAgICAgIHN0ck91
dHB1dCArPSBsaW5lICsgJ1xuJzsNCiAgICB9DQoNCiAgICB3aGlsZSAoKGxpbmUgPSBlci5yZWFk
TGluZSgpKSAhPSBudWxsKQ0KICAgIHsNCiAgICAgIFN5c3RlbS5vdXQucHJpbnRsbihsaW5lKTsN
CiAgICAgIHN0ckVycm9yICs9IGxpbmUgKyAnXG4nOw0KICAgIH0NCiAgICBpci5jbG9zZSgpOw0K
ICAgIGVyLmNsb3NlKCk7DQoNCiAgICBwcm9jZXNzLndhaXRGb3IoKTsNCg0KICB9DQoNCn0NCmNh
dGNoIChFeGNlcHRpb24gZSkNCnsNCiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZS50b1N0
cmluZygpKTsNCn0NCmZpbmFsbHkNCnsNCiAgaWYgKHN0clN5bmNocm9ub3VzLmVxdWFscygidHJ1
ZSIpICYmIHByb2Nlc3MgIT0gbnVsbCkNCiAgew0KICAgIGludCBzdGF0dXMgPSBwcm9jZXNzLmV4
aXRWYWx1ZSgpOw0KICAgIGlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJzdGF0dXMiLCBJbnRlZ2Vy
LnRvU3RyaW5nKHN0YXR1cykpOw0KICB9DQogIGlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJvdXRw
dXQiLCBzdHJPdXRwdXQpOw0KICBpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigiZXJyb3IiLCBzdHJF
cnJvcik7DQogIHByb2Nlc3MuZGVzdHJveSgpOw0KICBpZGNQaXBlbGluZS5kZXN0cm95KCk7DQp9
DQo=</value>
</Values>
