<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">invoke</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required folder</value>
    <value>[i] field:0:required service</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">DQpJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KU3RyaW5n
IHN0clNlcnZpY2VOYW1lID0gbnVsbDsNClN0cmluZyBzdHJGb2xkZXJOYW1lID0gbnVsbDsNCnRy
eQ0Kew0KICBpZiAoaWRjUGlwZWxpbmUuZmlyc3QoInNlcnZpY2UiKSkNCiAgew0KICAgIHN0clNl
cnZpY2VOYW1lID0gKFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsNCiAgfQ0KICBlbHNl
DQogIHsNCiAgICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiSW52YWxpZCBzZXJ2aWNlIG5h
bWUiKTsNCiAgfQ0KDQogIGlmIChpZGNQaXBlbGluZS5maXJzdCgiZm9sZGVyIikpDQogIHsNCiAg
ICBzdHJGb2xkZXJOYW1lID0gKFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsNCiAgfQ0K
ICBlbHNlDQogIHsNCiAgICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiSW52YWxpZCBmb2xk
ZXIgbmFtZSIpOw0KICB9DQoNCiAgaWYgKHN0clNlcnZpY2VOYW1lLmxlbmd0aCgpID09IDAgfHwg
c3RyRm9sZGVyTmFtZS5sZW5ndGgoKSA9PSAwKQ0KICAgIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0
aW9uKCJJbnZhbGlkIHNlcnZpY2UgbmFtZSIpOw0KDQogIFN0cmluZyBzdHJGdWxsU2VydmljZU5h
bWUgPSBzdHJGb2xkZXJOYW1lICsgIjoiICsgc3RyU2VydmljZU5hbWU7DQoNCiAgLy8gKioqIENo
ZWNrIGlmIHNlcnZpY2UgaXMgb24gdGhlIGFsbG93ZWQgbGlzdCAqKioNCiAgSURhdGEgaW4gPSBJ
RGF0YUZhY3RvcnkuY3JlYXRlKCk7DQogIElEYXRhQ3Vyc29yIGlkY0luID0gaW4uZ2V0Q3Vyc29y
KCk7DQogIGlkY0luLmluc2VydEFmdGVyKCJwYXJhbU5hbWUiLCAiYWxsb3dlZFNlcnZpY2VzIik7
DQogIGlkY0luLmluc2VydEFmdGVyKCJwYXJhbVZhbHVlIiwgc3RyRnVsbFNlcnZpY2VOYW1lKTsN
CiAgTlNOYW1lIG5zQ2hlY2tTZXJ2aWNlTmFtZSA9IE5TTmFtZS5jcmVhdGUoIlBTVXRpbGl0aWVz
LmNvbmZpZzpjaGVja1BhcmFtZXRlclZhbGlkaXR5Iik7DQogIGlkY0luLmRlc3Ryb3koKTsNCiAg
SURhdGEgb3V0Ow0KICBvdXQgPSBTZXJ2aWNlLmRvSW52b2tlKG5zQ2hlY2tTZXJ2aWNlTmFtZSwg
aW4pOw0KICBJRGF0YUN1cnNvciBpZGNPdXQgPSBvdXQuZ2V0Q3Vyc29yKCk7DQogIFN0cmluZyBz
dHJWYWxpZCA9IG51bGw7DQogIGlmIChpZGNPdXQuZmlyc3QoInZhbGlkIikpDQogIHsNCiAgICBz
dHJWYWxpZCA9IChTdHJpbmcpIGlkY091dC5nZXRWYWx1ZSgpOw0KICB9DQogIGlkY091dC5kZXN0
cm95KCk7DQoNCiAgaWYgKHN0clZhbGlkLmVxdWFscygiZmFsc2UiKSkNCiAgew0KICAgIHRocm93
IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJTcGVjaWZpZWQgc2VydmljZSBpcyBub3Qgb24gdGhlIGFs
bG93ZWQgbGlzdCBpbiB0aGUgUFNVdGlsaXRpZXMgY29uZmlndXJhdGlvbiBmaWxlISIpOw0KICB9
DQogIC8vICoqKiBFbmQgY2hlY2sgKioqDQoNCiAgTlNOYW1lIG5zTmFtZSA9IE5TTmFtZS5jcmVh
dGUoc3RyRnVsbFNlcnZpY2VOYW1lKTsNCg0KICBJRGF0YSByZXN1bHRzID0gU2VydmljZS5kb0lu
dm9rZShuc05hbWUsIHBpcGVsaW5lKTsNCiAgSURhdGFVdGlsLm1lcmdlKHJlc3VsdHMsIHBpcGVs
aW5lKTsNCg0KfQ0KY2F0Y2ggKEV4Y2VwdGlvbiBlKQ0Kew0KICB0aHJvdyBuZXcgU2VydmljZUV4
Y2VwdGlvbihlLmdldE1lc3NhZ2UoKSk7DQp9DQpmaW5hbGx5DQp7DQogIGlkY1BpcGVsaW5lLmRl
c3Ryb3koKTsNCn0NCg==</value>
</Values>
