<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">loadPSUtilitiesConfig</value>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5DQp7DQogIC8vIFN0cmluZyBzdHJGaWxlU2VwYXJhdG9yID0NCiAgLy8gKFN5c3RlbS5nZXRQ
cm9wZXJ0aWVzKCkpLmdldFByb3BlcnR5KCJmaWxlLnNlcGFyYXRvciIpOw0KICAvLyBTdHJpbmcg
c3RyQ3VycmVudERpciA9DQogIC8vIChTeXN0ZW0uZ2V0UHJvcGVydGllcygpKS5nZXRQcm9wZXJ0
eSgidXNlci5kaXIiKTsNCiAgU3RyaW5nIHN0ckZpbGVuYW1lID0gInBhY2thZ2VzL1BTVXRpbGl0
aWVzL2NvbmZpZy9QU1V0aWxpdGllcy5jbmYiOw0KDQogIEZpbGUgZmlsZSA9IG5ldyBGaWxlKHN0
ckZpbGVuYW1lKTsNCiAgaWYgKGZpbGUuY2FuUmVhZCgpKQ0KICB7DQogICAgSW5wdXRTdHJlYW0g
c3RyZWFtID0gbmV3IGphdmEuaW8uQnVmZmVyZWRJbnB1dFN0cmVhbShuZXcgamF2YS5pby5GaWxl
SW5wdXRTdHJlYW0oZmlsZSkpOw0KDQogICAgdHJ5DQogICAgew0KICAgICAgcHJvcGVydGllcy5s
b2FkKHN0cmVhbSk7DQogICAgICBTeXN0ZW0ub3V0LnByaW50bG4oIlN1Y2Nlc3NmdWxseSBsb2Fk
ZWQgUFNVdGlsaXRpZXMgY29uZmlndXJhdGlvbiBmaWxlIGludG8gbWVtb3J5Iik7DQogICAgfQ0K
ICAgIGZpbmFsbHkNCiAgICB7DQogICAgICBzdHJlYW0uY2xvc2UoKTsNCiAgICB9DQoNCiAgfQ0K
ICBlbHNlDQogIHsNCiAgICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiQ291bGQgbm90IHJl
YWQgcHJvcGVydGllcyBmaWxlOiAiICsgc3RyRmlsZW5hbWUpOw0KICB9DQp9DQpjYXRjaCAoRXhj
ZXB0aW9uIGUpDQp7DQogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJFcnJvciByZWFkaW5n
IHByb3BlcnRpZXMgZmlsZTogIiArIGUpOw0KfQ0KDQo=</value>
</Values>
