<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">extractResourceFromServiceName</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQpTdHJpbmcgcmVz
b3VyY2VOYW1lID0gInVuZGVmaW5lZCI7DQp0cnkgew0KCVN0cmluZyBzZXJ2aWNlRnFuID0gSURh
dGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUMsICJzZXJ2aWNlRnFuIik7DQoJU3RyaW5nIGZvbGRl
ckZxbiA9IHNlcnZpY2VGcW4uc3Vic3RyaW5nKDAsIHNlcnZpY2VGcW4uaW5kZXhPZigiOiIpKTsN
CglyZXNvdXJjZU5hbWUgPSBmb2xkZXJGcW4uc3Vic3RyaW5nKGZvbGRlckZxbi5sYXN0SW5kZXhP
ZigiLiIpKzEsIGZvbGRlckZxbi5sZW5ndGgoKSk7DQp9IGNhdGNoKEV4Y2VwdGlvbiBlKSB7DQoJ
Ly8gZG8gbm90aGluZw0KfQ0KSURhdGFVdGlsLnB1dChwaXBlbGluZUMsICJyZXNvdXJjZU5hbWUi
LCByZXNvdXJjZU5hbWUpOw0KcGlwZWxpbmVDLmRlc3Ryb3koKTsNCgk=</value>
</Values>
