<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">readPropertiesFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required filename</value>
    <value>[o] object:0:required property</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">DQpJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KU3RyaW5n
IHN0ckZpbGVuYW1lID0gbnVsbDsNCmlmIChpZGNQaXBlbGluZS5maXJzdCgiZmlsZW5hbWUiKSkN
CnsNCiAgc3RyRmlsZW5hbWUgPSAoU3RyaW5nKSBpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOw0KfQ0K
ZWxzZQ0Kew0KICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiQ291bGQgbm90IHJlYWQgUHJv
cGVydGllcyBmaWxlLiAgZmlsZW5hbWUgaXMgbnVsbCEiKTsNCn0NCg0KdHJ5DQp7DQogIEZpbGUg
ZmlsZSA9IG5ldyBGaWxlKHN0ckZpbGVuYW1lKTsNCiAgaWYgKGZpbGUuY2FuUmVhZCgpKQ0KICB7
DQogICAgUHJvcGVydGllcyBwcm9wZXJ0eSA9IG5ldyBQcm9wZXJ0aWVzKCk7DQogICAgSW5wdXRT
dHJlYW0gc3RyZWFtID0gbmV3IGphdmEuaW8uQnVmZmVyZWRJbnB1dFN0cmVhbShuZXcgamF2YS5p
by5GaWxlSW5wdXRTdHJlYW0oZmlsZSkpOw0KDQogICAgdHJ5DQogICAgew0KICAgICAgcHJvcGVy
dHkubG9hZChzdHJlYW0pOw0KICAgIH0NCiAgICBmaW5hbGx5DQogICAgew0KICAgICAgc3RyZWFt
LmNsb3NlKCk7DQogICAgfQ0KDQogICAgDQogICAgRW51bWVyYXRpb24gZW51bWVyYXRpb24gPSBw
cm9wZXJ0eS5wcm9wZXJ0eU5hbWVzKCk7DQogICAgd2hpbGUgKGVudW1lcmF0aW9uLmhhc01vcmVF
bGVtZW50cygpKQ0KICAgIHsNCiAgICAgIFN0cmluZyBzdHJQcm9wZXJ0eU5hbWUgPSAoU3RyaW5n
KWVudW1lcmF0aW9uLm5leHRFbGVtZW50KCk7DQogICAgICBTdHJpbmcgc3RyUHJvcGVydHlWYWx1
ZSA9IChTdHJpbmcpIHByb3BlcnR5LmdldFByb3BlcnR5KHN0clByb3BlcnR5TmFtZSk7DQogICAg
ICBpZGNQaXBlbGluZS5pbnNlcnRBZnRlcihzdHJQcm9wZXJ0eU5hbWUsIHN0clByb3BlcnR5VmFs
dWUpOw0KICAgIH0NCg0KICAgIC8vIFB1dCBlbnRpcmUgcHJvcGVydHkgb2JqZWN0IGludG8gdGhl
IG91dHB1dCBwaXBlbGluZQ0KICAgIGlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJwcm9wZXJ0eSIs
IHByb3BlcnR5KTsNCiAgfQ0KICBlbHNlDQogIHsNCiAgICB0aHJvdyBuZXcgU2VydmljZUV4Y2Vw
dGlvbigiQ291bGQgbm90IHJlYWQgcHJvcGVydGllcyBmaWxlOiAiICsgc3RyRmlsZW5hbWUpOw0K
ICB9DQp9DQpjYXRjaCAoRXhjZXB0aW9uIGUpDQp7DQogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0
aW9uKCJFcnJvciByZWFkaW5nIHByb3BlcnRpZXMgZmlsZTogIiArIGUpOw0KfQ0KZmluYWxseQ0K
ew0KICBpZGNQaXBlbGluZS5kZXN0cm95KCk7DQp9DQoNCg==</value>
</Values>
