<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">incrementDate</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required startingDate</value>
    <value>[i] field:0:required startingDateFormat</value>
    <value>[i] field:0:required endingDateFormat</value>
    <value>[i] field:0:optional addYears</value>
    <value>[i] field:0:optional addMonths</value>
    <value>[i] field:0:optional addDays</value>
    <value>[i] field:0:optional addHours</value>
    <value>[i] field:0:optional addMinutes</value>
    <value>[i] field:0:optional addSeconds</value>
    <value>[o] field:0:required endingDate</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">DQpJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KDQpTdHJp
bmcgc3RyU3RhcnRpbmdEYXRlID0gbnVsbDsNCmlmIChpZGNQaXBlbGluZS5maXJzdCgic3RhcnRp
bmdEYXRlIikpDQp7DQogIHN0clN0YXJ0aW5nRGF0ZSA9IChTdHJpbmcpIGlkY1BpcGVsaW5lLmdl
dFZhbHVlKCk7DQp9DQplbHNlDQp7DQogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJzdGFy
dGluZ0RhdGUgbXVzdCBiZSBzdXBwbGllZCEiKTsNCn0NClN0cmluZyBzdHJTdGFydGluZ0RhdGVG
b3JtYXQgPSBudWxsOw0KaWYgKGlkY1BpcGVsaW5lLmZpcnN0KCJzdGFydGluZ0RhdGVGb3JtYXQi
KSkNCnsNCiAgc3RyU3RhcnRpbmdEYXRlRm9ybWF0ID0gKFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0
VmFsdWUoKTsNCn0NCmVsc2UNCnsNCiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oInN0YXJ0
aW5nRGF0ZUZvcm1hdCBtdXN0IGJlIHN1cHBsaWVkISIpOw0KfQ0KU3RyaW5nIHN0ckVuZGluZ0Rh
dGVGb3JtYXQgPSBudWxsOw0KaWYgKGlkY1BpcGVsaW5lLmZpcnN0KCJlbmRpbmdEYXRlRm9ybWF0
IikpDQp7DQogIHN0ckVuZGluZ0RhdGVGb3JtYXQgPSAoU3RyaW5nKSBpZGNQaXBlbGluZS5nZXRW
YWx1ZSgpOw0KfQ0KZWxzZQ0Kew0KICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiZW5kaW5n
RGF0ZUZvcm1hdCBtdXN0IGJlIHN1cHBsaWVkISIpOw0KfQ0KDQpTdHJpbmcgc3RyQWRkWWVhcnMg
PSBudWxsOw0KU3RyaW5nIHN0ckFkZE1vbnRocyA9IG51bGw7DQpTdHJpbmcgc3RyQWRkRGF5cyA9
IG51bGw7DQpTdHJpbmcgc3RyQWRkSG91cnMgPSBudWxsOw0KU3RyaW5nIHN0ckFkZE1pbnV0ZXMg
PSBudWxsOw0KU3RyaW5nIHN0ckFkZFNlY29uZHMgPSBudWxsOw0KDQppZiAoaWRjUGlwZWxpbmUu
Zmlyc3QoImFkZFllYXJzIikpDQp7DQogIHN0ckFkZFllYXJzID0gKFN0cmluZykgaWRjUGlwZWxp
bmUuZ2V0VmFsdWUoKTsNCn0NCmlmIChpZGNQaXBlbGluZS5maXJzdCgiYWRkTW9udGhzIikpDQp7
DQogIHN0ckFkZE1vbnRocyA9IChTdHJpbmcpIGlkY1BpcGVsaW5lLmdldFZhbHVlKCk7DQp9DQpp
ZiAoaWRjUGlwZWxpbmUuZmlyc3QoImFkZERheXMiKSkNCnsNCiAgc3RyQWRkRGF5cyA9IChTdHJp
bmcpIGlkY1BpcGVsaW5lLmdldFZhbHVlKCk7DQp9DQppZiAoaWRjUGlwZWxpbmUuZmlyc3QoImFk
ZEhvdXJzIikpDQp7DQogIHN0ckFkZEhvdXJzID0gKFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0VmFs
dWUoKTsNCn0NCmlmIChpZGNQaXBlbGluZS5maXJzdCgiYWRkTWludXRlcyIpKQ0Kew0KICBzdHJB
ZGRNaW51dGVzID0gKFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsNCn0NCmlmIChpZGNQ
aXBlbGluZS5maXJzdCgiYWRkU2Vjb25kcyIpKQ0Kew0KICBzdHJBZGRTZWNvbmRzID0gKFN0cmlu
ZykgaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsNCn0NCg0KU2ltcGxlRGF0ZUZvcm1hdCBzc2RmID0g
bmV3IFNpbXBsZURhdGVGb3JtYXQoc3RyU3RhcnRpbmdEYXRlRm9ybWF0KTsNCg0KRGF0ZSBzdGFy
dGluZ0RhdGUgPSBudWxsOw0KdHJ5DQp7DQogIHN0YXJ0aW5nRGF0ZSA9IHNzZGYucGFyc2Uoc3Ry
U3RhcnRpbmdEYXRlKTsNCn0NCmNhdGNoIChFeGNlcHRpb24gZSkNCnsNCiAgdGhyb3cgbmV3IFNl
cnZpY2VFeGNlcHRpb24oZS50b1N0cmluZygpKTsNCn0NCg0KR3JlZ29yaWFuQ2FsZW5kYXIgZ2Mg
PSBuZXcgR3JlZ29yaWFuQ2FsZW5kYXIoKTsNCmdjLnNldFRpbWUoc3RhcnRpbmdEYXRlKTsNCg0K
aWYgKHN0ckFkZFllYXJzICE9IG51bGwpDQp7DQogIGdjLmFkZChDYWxlbmRhci5ZRUFSLCBJbnRl
Z2VyLnBhcnNlSW50KHN0ckFkZFllYXJzKSk7DQp9DQppZiAoc3RyQWRkTW9udGhzICE9IG51bGwp
DQp7DQogIGdjLmFkZChDYWxlbmRhci5NT05USCwgSW50ZWdlci5wYXJzZUludChzdHJBZGRNb250
aHMpKTsNCn0NCmlmIChzdHJBZGREYXlzICE9IG51bGwpDQp7DQogIGdjLmFkZChDYWxlbmRhci5E
QVlfT0ZfTU9OVEgsIEludGVnZXIucGFyc2VJbnQoc3RyQWRkRGF5cykpOw0KfQ0KaWYgKHN0ckFk
ZEhvdXJzICE9IG51bGwpDQp7DQogIGdjLmFkZChDYWxlbmRhci5IT1VSX09GX0RBWSwgSW50ZWdl
ci5wYXJzZUludChzdHJBZGRIb3VycykpOw0KfQ0KaWYgKHN0ckFkZE1pbnV0ZXMgIT0gbnVsbCkN
CnsNCiAgZ2MuYWRkKENhbGVuZGFyLk1JTlVURSwgSW50ZWdlci5wYXJzZUludChzdHJBZGRNaW51
dGVzKSk7DQp9DQppZiAoc3RyQWRkU2Vjb25kcyAhPSBudWxsKQ0Kew0KICBnYy5hZGQoQ2FsZW5k
YXIuU0VDT05ELCBJbnRlZ2VyLnBhcnNlSW50KHN0ckFkZFNlY29uZHMpKTsNCn0NCg0KRGF0ZSBl
bmRpbmdEYXRlID0gZ2MuZ2V0VGltZSgpOw0KU2ltcGxlRGF0ZUZvcm1hdCBlc2RmID0gbmV3IFNp
bXBsZURhdGVGb3JtYXQoc3RyRW5kaW5nRGF0ZUZvcm1hdCk7DQpTdHJpbmcgc3RyRW5kaW5nRGF0
ZSA9IGVzZGYuZm9ybWF0KGVuZGluZ0RhdGUpOw0KDQppZGNQaXBlbGluZS5pbnNlcnRBZnRlcigi
ZW5kaW5nRGF0ZSIsIHN0ckVuZGluZ0RhdGUpOw0KaWRjUGlwZWxpbmUuZGVzdHJveSgpOw0K</value>
</Values>
