<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">zipFiles2</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:1:required files</value>
    <value>[i] field:0:required output</value>
    <value>[o] field:0:required message</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRjID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQpTdHJpbmdbXSBmaWxlcyA9
IG51bGw7DQpTdHJpbmcgb3V0cHV0ID0gbnVsbDsNClN0cmluZyBtZXNzYWdlID0gIiI7DQppZiAo
aWRjLmZpcnN0KCJmaWxlcyIpKQ0Kew0KICBmaWxlcyA9IChTdHJpbmdbXSkgaWRjLmdldFZhbHVl
KCk7DQp9DQppZiAoaWRjLmZpcnN0KCJvdXRwdXQiKSkNCnsNCiAgb3V0cHV0ID0gKFN0cmluZykg
aWRjLmdldFZhbHVlKCk7DQp9DQppZGMuZGVzdHJveSgpOw0KDQovLyAqKiogQ2hlY2sgaWYgcGF0
aHMgYXJlIG9uIHRoZSBhbGxvd2VkIGxpc3QgKioqDQp0cnkNCnsNCiAgZm9yIChpbnQgaSA9IDA7
IGkgPCBmaWxlcy5sZW5ndGg7IGkrKykNCiAgew0KICAgIGlmICghY2hlY2tQYXRoVmFsaWRpdHko
ZmlsZXNbaV0sICJyZWFkIikpDQogICAgew0KICAgICAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRp
b24oIlNwZWNpZmllZCBwYXRoIGlzIG5vdCBvbiB0aGUgcmVhZCBhbGxvd2VkIGxpc3QgaW4gdGhl
IFBTVXRpbGl0aWVzIGNvbmZpZ3VyYXRpb24gZmlsZSEiKTsNCiAgICB9DQogIH0NCg0KICBpZiAo
IWNoZWNrUGF0aFZhbGlkaXR5KG91dHB1dCwgIndyaXRlIikpDQogIHsNCiAgICB0aHJvdyBuZXcg
U2VydmljZUV4Y2VwdGlvbigiU3BlY2lmaWVkIHBhdGggaXMgbm90IG9uIHRoZSB3cml0ZSBhbGxv
d2VkIGxpc3QgaW4gdGhlIFBTVXRpbGl0aWVzIGNvbmZpZ3VyYXRpb24gZmlsZSEiKTsNCiAgfQ0K
fQ0KY2F0Y2ggKEV4Y2VwdGlvbiBlKQ0Kew0KICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihl
LmdldE1lc3NhZ2UoKSk7DQp9DQovLyAqKiogRW5kIGNoZWNrICoqKg0KDQp0cnkNCnsNCiAgWmlw
T3V0cHV0U3RyZWFtIHpvcyA9IG5ldyBaaXBPdXRwdXRTdHJlYW0obmV3IEZpbGVPdXRwdXRTdHJl
YW0ob3V0cHV0KSk7DQogIGZvciAoaW50IGkgPSAwOyBpIDwgZmlsZXMubGVuZ3RoOyBpKyspDQog
IHsNCiAgICBTeXN0ZW0ub3V0LnByaW50bG4oIk5vdyBhZGRpbmcgIiArIGZpbGVzW2ldKTsNCg0K
ICAgIHpvcy5wdXROZXh0RW50cnkobmV3IFppcEVudHJ5KGZpbGVzW2ldKSk7DQogICAgdHJ5DQog
ICAgew0KICAgICAgRmlsZUlucHV0U3RyZWFtIGZpcyA9IG5ldyBGaWxlSW5wdXRTdHJlYW0oZmls
ZXNbaV0pOw0KICAgICAgYnl0ZVtdIGIgPSBuZXcgYnl0ZVs2NTUzNl07DQogICAgICBpbnQgYnl0
ZVJlYWQgPSAwOw0KICAgICAgd2hpbGUgKChieXRlUmVhZCA9IGZpcy5yZWFkKGIpKSAhPSAtMSkN
CiAgICAgIHsgLy8gVGlsbCBub3QgZW5kIG9mIGZpbGUNCiAgICAgICAgem9zLndyaXRlKGIsIDAs
IGJ5dGVSZWFkKTsNCiAgICAgIH0NCiAgICAgIGZpcy5jbG9zZSgpOw0KICAgIH0NCiAgICBjYXRj
aCAoRXhjZXB0aW9uIGUpDQogICAgew0KICAgICAgbWVzc2FnZSArPSBmaWxlc1tpXSArICIgIjsN
CiAgICB9DQogICAgem9zLmNsb3NlRW50cnkoKTsNCiAgfQ0KICB6b3MuY2xvc2UoKTsNCn0NCmNh
dGNoIChFeGNlcHRpb24gZSkNCnsNCiAgZS5wcmludFN0YWNrVHJhY2UoKTsNCn0NCg0KaWYgKCFt
ZXNzYWdlLmVxdWFscygiIikpDQp7DQogIElEYXRhQ3Vyc29yIGlkY28gPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsNCiAgaWRjLmluc2VydEFmdGVyKCJtZXNzYWdlIiwgIkNhbiBub3QgemlwICIgKyBt
ZXNzYWdlKTsNCiAgaWRjLmRlc3Ryb3koKTsNCn0NCg==</value>
</Values>
