<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">calculateDateDifference</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required startDateTime</value>
    <value>[i] field:0:required endDateTime</value>
    <value>[i] field:0:required startDateFormat</value>
    <value>[i] field:0:required endDateFormat</value>
    <value>[o] field:0:required dateDifferenceSec</value>
    <value>[o] field:0:required dateDifferenceMin</value>
    <value>[o] field:0:required dateDifferenceHr</value>
    <value>[o] field:0:required dateDifferenceDay</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">DQovLyBwaXBlbGluZQ0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsNClN0cmluZyBzdGFydERhdGVUaW1lID0gIiI7DQpTdHJpbmcgZW5kRGF0ZVRpbWUg
PSAiIjsNClN0cmluZyBzdGFydERhdGVGb3JtYXQgPSAiIjsNClN0cmluZyBlbmREYXRlRm9ybWF0
ID0gIiI7DQppZiAocGlwZWxpbmVDdXJzb3IuZmlyc3QoInN0YXJ0RGF0ZVRpbWUiKSkNCnsNCiAg
c3RhcnREYXRlVGltZSA9IChTdHJpbmcpIHBpcGVsaW5lQ3Vyc29yLmdldFZhbHVlKCk7DQp9DQpp
ZiAocGlwZWxpbmVDdXJzb3IuZmlyc3QoImVuZERhdGVUaW1lIikpDQp7DQogIGVuZERhdGVUaW1l
ID0gKFN0cmluZykgcGlwZWxpbmVDdXJzb3IuZ2V0VmFsdWUoKTsNCn0NCmlmIChwaXBlbGluZUN1
cnNvci5maXJzdCgic3RhcnREYXRlRm9ybWF0IikpDQp7DQogIHN0YXJ0RGF0ZUZvcm1hdCA9IChT
dHJpbmcpIHBpcGVsaW5lQ3Vyc29yLmdldFZhbHVlKCk7DQp9DQppZiAocGlwZWxpbmVDdXJzb3Iu
Zmlyc3QoImVuZERhdGVGb3JtYXQiKSkNCnsNCiAgZW5kRGF0ZUZvcm1hdCA9IChTdHJpbmcpIHBp
cGVsaW5lQ3Vyc29yLmdldFZhbHVlKCk7DQp9DQoNCmlmIChzdGFydERhdGVUaW1lLmVxdWFscygi
IikgfHwgZW5kRGF0ZVRpbWUuZXF1YWxzKCIiKSkNCiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRp
b24oIkRhdGVzIGNhbm5vdCBiZSBudWxsIik7DQppZiAoc3RhcnREYXRlRm9ybWF0LmVxdWFscygi
IikgfHwgZW5kRGF0ZUZvcm1hdC5lcXVhbHMoIiIpKQ0KICB0aHJvdyBuZXcgU2VydmljZUV4Y2Vw
dGlvbigiRGF0ZSBmb3JtYXRzIGNhbm5vdCBiZSBudWxsIik7DQoNCnBpcGVsaW5lQ3Vyc29yLmRl
c3Ryb3koKTsNCg0KdHJ5DQp7DQogIFNpbXBsZURhdGVGb3JtYXQgc2RmID0gbmV3IFNpbXBsZURh
dGVGb3JtYXQoc3RhcnREYXRlRm9ybWF0KTsNCiAgRGF0ZSBzZHQgPSBzZGYucGFyc2Uoc3RhcnRE
YXRlVGltZSk7DQogIFNpbXBsZURhdGVGb3JtYXQgZWRmID0gbmV3IFNpbXBsZURhdGVGb3JtYXQo
ZW5kRGF0ZUZvcm1hdCk7DQogIERhdGUgZWR0ID0gZWRmLnBhcnNlKGVuZERhdGVUaW1lKTsNCiAg
bG9uZyB0aW1lZGlmZiA9IGVkdC5nZXRUaW1lKCkgLSBzZHQuZ2V0VGltZSgpOw0KDQogIC8vIFNp
bXBsZURhdGVGb3JtYXQgc3NkZiA9IG5ldyBTaW1wbGVEYXRlRm9ybWF0KCJISDptbTpzcyIpOw0K
ICAvLyBDYWxlbmRhciBjYWwgPSBDYWxlbmRhci5nZXRJbnN0YW5jZSgpOw0KICAvLyBjYWwuY2xl
YXIoKTsNCiAgLy8gY2FsLnNldChDYWxlbmRhci5TRUNPTkQsIChpbnQpIHRpbWVkaWZmIC8xMDAw
KTsNCg0KICAvLyBEYXRlIG5ld0RhdGVUaW1lID0gY2FsLmdldFRpbWUoKTsNCiAgLy8gU3RyaW5n
IGRpc3BsYXlUaW1lPW51bGw7DQoNCiAgLy8gaWYgKGNhbC5nZXQoQ2FsZW5kYXIuREFZX09GX1lF
QVIpID4gMSApDQogIC8vIGRpc3BsYXlUaW1lID0gc3NkZi5mb3JtYXQobmV3RGF0ZVRpbWUpICsg
IiBhbmQgIiArDQogIC8vIChjYWwuZ2V0KENhbGVuZGFyLkRBWV9PRl9ZRUFSKS0xKSArICIgRGF5
KHMpIiA7DQogIC8vIGVsc2UNCiAgLy8gZGlzcGxheVRpbWUgPSBzc2RmLmZvcm1hdChuZXdEYXRl
VGltZSk7DQoNCiAgU3RyaW5nIGRpc3BsYXlUaW1lU2VjID0gTG9uZy50b1N0cmluZyh0aW1lZGlm
ZiAvIDEwMDApOw0KICBTdHJpbmcgZGlzcGxheVRpbWVNaW4gPSBMb25nLnRvU3RyaW5nKHRpbWVk
aWZmIC8gNjAwMDApOw0KICBTdHJpbmcgZGlzcGxheVRpbWVIciA9IExvbmcudG9TdHJpbmcodGlt
ZWRpZmYgLyAzNjAwMDAwKTsNCiAgU3RyaW5nIGRpc3BsYXlUaW1lRGF5ID0gTG9uZy50b1N0cmlu
Zyh0aW1lZGlmZiAvIDg2NDAwMDAwKTsNCg0KICAvLyBwaXBlbGluZQ0KICBJRGF0YUN1cnNvciBw
aXBlbGluZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQogIHBpcGVsaW5lQ3Vyc29y
XzEubGFzdCgpOw0KICBwaXBlbGluZUN1cnNvcl8xLmluc2VydEFmdGVyKCJkYXRlRGlmZmVyZW5j
ZVNlYyIsIGRpc3BsYXlUaW1lU2VjKTsNCiAgcGlwZWxpbmVDdXJzb3JfMS5pbnNlcnRBZnRlcigi
ZGF0ZURpZmZlcmVuY2VNaW4iLCBkaXNwbGF5VGltZU1pbik7DQogIHBpcGVsaW5lQ3Vyc29yXzEu
aW5zZXJ0QWZ0ZXIoImRhdGVEaWZmZXJlbmNlSHIiLCBkaXNwbGF5VGltZUhyKTsNCiAgcGlwZWxp
bmVDdXJzb3JfMS5pbnNlcnRBZnRlcigiZGF0ZURpZmZlcmVuY2VEYXkiLCBkaXNwbGF5VGltZURh
eSk7DQogIHBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOw0KfQ0KY2F0Y2ggKFBhcnNlRXhjZXB0
aW9uIGUpDQp7DQogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJFcnJvciBwYXJzaW5nIHRo
ZSBkYXRlIHRpbWU6ICIgKyBlKTsNCn0NCg==</value>
</Values>
