<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">doInvoke</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required serviceNS</value>
    <value>[i] record:0:required input</value>
    <value>[o] record:0:required output</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">DQpJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KSURhdGEg
aW5wdXREYXRhID0gbnVsbDsNCklEYXRhIG91dHB1dERhdGEgPSBudWxsOw0KU3RyaW5nIHN0clNl
cnZpY2VOYW1lID0gbnVsbDsNCg0KdHJ5DQp7DQogIC8vICoqKiBDaGVjayBpZiBzZXJ2aWNlIGlz
IG9uIHRoZSBhbGxvd2VkIGxpc3QgKioqDQogIElEYXRhIGluID0gSURhdGFGYWN0b3J5LmNyZWF0
ZSgpOw0KICBJRGF0YUN1cnNvciBpZGNJbiA9IGluLmdldEN1cnNvcigpOw0KICBpZGNJbi5pbnNl
cnRBZnRlcigicGFyYW1OYW1lIiwgImFsbG93ZWRTZXJ2aWNlcyIpOw0KICBpZGNJbi5pbnNlcnRB
ZnRlcigicGFyYW1WYWx1ZSIsIHN0clNlcnZpY2VOYW1lKTsNCiAgTlNOYW1lIG5zQ2hlY2tTZXJ2
aWNlTmFtZSA9IE5TTmFtZS5jcmVhdGUoIlBTVXRpbGl0aWVzLmNvbmZpZzpjaGVja1BhcmFtZXRl
clZhbGlkaXR5Iik7DQogIGlkY0luLmRlc3Ryb3koKTsNCiAgSURhdGEgb3V0Ow0KICBvdXQgPSBT
ZXJ2aWNlLmRvSW52b2tlKG5zQ2hlY2tTZXJ2aWNlTmFtZSwgaW4pOw0KICBJRGF0YUN1cnNvciBp
ZGNPdXQgPSBvdXQuZ2V0Q3Vyc29yKCk7DQogIFN0cmluZyBzdHJWYWxpZCA9IG51bGw7DQogIGlm
IChpZGNPdXQuZmlyc3QoInZhbGlkIikpDQogIHsNCiAgICBzdHJWYWxpZCA9IChTdHJpbmcpIGlk
Y091dC5nZXRWYWx1ZSgpOw0KICB9DQogIGlkY091dC5kZXN0cm95KCk7DQoNCiAgaWYgKHN0clZh
bGlkLmVxdWFscygiZmFsc2UiKSkNCiAgew0KICAgIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9u
KCJTcGVjaWZpZWQgc2VydmljZSBpcyBub3Qgb24gdGhlIGFsbG93ZWQgbGlzdCBpbiB0aGUgUFNV
dGlsaXRpZXMgY29uZmlndXJhdGlvbiBmaWxlISIpOw0KICB9DQogIC8vICoqKiBFbmQgY2hlY2sg
KioqDQoNCiAgaWYgKGlkY1BpcGVsaW5lLmZpcnN0KCJzZXJ2aWNlTlMiKSkNCiAgew0KICAgIHN0
clNlcnZpY2VOYW1lID0gKFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsNCiAgfQ0KICBl
bHNlDQogIHsNCiAgICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigibWlzc2luZyBzZXJ2aWNl
IG5hbWUiKTsNCiAgfQ0KDQogIGlmIChzdHJTZXJ2aWNlTmFtZS5sZW5ndGgoKSA9PSAwKQ0KICAg
IHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJJbnZhbGlkIHNlcnZpY2UgbmFtZSIpOw0KDQog
IGlmIChpZGNQaXBlbGluZS5maXJzdCgiaW5wdXQiKSkNCiAgICBpbnB1dERhdGEgPSAoSURhdGEp
IGlkY1BpcGVsaW5lLmdldFZhbHVlKCk7DQoNCiAgTlNOYW1lIG5zTmFtZSA9IE5TTmFtZS5jcmVh
dGUoc3RyU2VydmljZU5hbWUpOw0KDQogIG91dHB1dERhdGEgPSBTZXJ2aWNlLmRvSW52b2tlKG5z
TmFtZSwgaW5wdXREYXRhKTsNCg0KICBpZiAob3V0cHV0RGF0YSAhPSBudWxsKQ0KICAgIGlkY1Bp
cGVsaW5lLmluc2VydEFmdGVyKCJvdXRwdXQiLCBvdXRwdXREYXRhKTsNCg0KfQ0KY2F0Y2ggKEV4
Y2VwdGlvbiBlKQ0Kew0KICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlKTsNCn0NCmZpbmFs
bHkNCnsNCiAgaWRjUGlwZWxpbmUuZGVzdHJveSgpOw0KfQ0K</value>
</Values>
