<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">bytesToFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required filename</value>
    <value>[i] object:0:required bytes</value>
    <value>[i] field:0:required append {"true","false"}</value>
    <value>[o] field:0:required fullpath</value>
    <value>[o] field:0:required length</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRjUGlwZWxpbmUgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCg0KYnl0ZVtd
IGJ5dGVzID0gbnVsbDsNClN0cmluZyBzdHJGaWxlbmFtZSA9IG51bGw7DQoNCmlmIChpZGNQaXBl
bGluZS5maXJzdCgiYnl0ZXMiKSkNCnsNCiAgYnl0ZXMgPSAoYnl0ZVtdKSBpZGNQaXBlbGluZS5n
ZXRWYWx1ZSgpOw0KfQ0KZWxzZQ0Kew0KICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiSW5w
dXQgcGFyYW1ldGVyIFwnYnl0ZXNcJyB3YXMgbm90IGZvdW5kLiIpOw0KfQ0KaWYgKGlkY1BpcGVs
aW5lLmZpcnN0KCJmaWxlbmFtZSIpKQ0Kew0KICBzdHJGaWxlbmFtZSA9IChTdHJpbmcpIGlkY1Bp
cGVsaW5lLmdldFZhbHVlKCk7DQp9DQplbHNlDQp7DQogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0
aW9uKCJJbnB1dCBwYXJhbWV0ZXIgXCdmaWxlbmFtZVwnIHdhcyBub3QgZm91bmQuIik7DQp9DQpi
b29sZWFuIGEgPSBpZGNQaXBlbGluZS5maXJzdCgiYXBwZW5kIikgPyBCb29sZWFuLnZhbHVlT2Yo
KFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKSkuYm9vbGVhblZhbHVlKCkgOiBmYWxzZTsN
Cg0KLy8gKioqIENoZWNrIGlmIHBhdGggaXMgb24gdGhlIGFsbG93ZWQgbGlzdCAqKioNCnRyeQ0K
ew0KICBpZiAoIWNoZWNrUGF0aFZhbGlkaXR5KHN0ckZpbGVuYW1lLCAid3JpdGUiKSkNCiAgew0K
ICAgIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJTcGVjaWZpZWQgcGF0aCBpcyBub3Qgb24g
dGhlIHdyaXRlIGFsbG93ZWQgbGlzdCBpbiB0aGUgUFNVdGlsaXRpZXMgY29uZmlndXJhdGlvbiBm
aWxlISIpOw0KICB9DQp9DQpjYXRjaCAoRXhjZXB0aW9uIGUpDQp7DQogIHRocm93IG5ldyBTZXJ2
aWNlRXhjZXB0aW9uKGUuZ2V0TWVzc2FnZSgpKTsNCn0NCi8vICoqKiBFbmQgY2hlY2sgKioqDQoN
CkZpbGUgZmlsZSA9IG5ldyBGaWxlKHN0ckZpbGVuYW1lKTsNClN0cmluZyBiYXNlbmFtZSA9IGZp
bGUuZ2V0TmFtZSgpOw0KDQpTdHJpbmcgZnVsbHBhdGggPSBudWxsOw0KdHJ5DQp7DQogIEZpbGUg
cGFyZW50ID0gZmlsZS5nZXRDYW5vbmljYWxGaWxlKCkuZ2V0UGFyZW50RmlsZSgpOw0KICBGaWxl
IHRhcmdldERpciA9IHBhcmVudDsNCg0KICBpZiAoIXRhcmdldERpci5leGlzdHMoKSkNCiAgew0K
ICAgIHRhcmdldERpci5ta2RpcnMoKTsNCiAgfQ0KICBmaWxlID0gbmV3IEZpbGUodGFyZ2V0RGly
LCBiYXNlbmFtZSk7DQogIGZ1bGxwYXRoID0gZmlsZS5nZXRDYW5vbmljYWxQYXRoKCk7DQogIEZp
bGVPdXRwdXRTdHJlYW0gd3JpdGVyID0gbmV3IEZpbGVPdXRwdXRTdHJlYW0oZmlsZS5nZXRDYW5v
bmljYWxQYXRoKCksIGEpOyAvLyBhcHBlbmQNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC8vIG9yDQog
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAvLyBub3QNCiAgd3JpdGVyLndyaXRlKGJ5dGVzKTsNCiAgd3Jp
dGVyLmNsb3NlKCk7DQp9DQpjYXRjaCAoSU9FeGNlcHRpb24gZSkNCnsNCiAgdGhyb3cgbmV3IFNl
cnZpY2VFeGNlcHRpb24oZSk7DQp9DQoNCmlkY1BpcGVsaW5lLmxhc3QoKTsNCmlkY1BpcGVsaW5l
Lmluc2VydEFmdGVyKCJmdWxscGF0aCIsIGZ1bGxwYXRoKTsNCmlkY1BpcGVsaW5lLmluc2VydEFm
dGVyKCJsZW5ndGgiLCAiIiArIGJ5dGVzLmxlbmd0aCk7DQppZGNQaXBlbGluZS5kZXN0cm95KCk7
DQo=</value>
</Values>
