<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getDataFromMemory</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required MemoryKey</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gR2V0IGN1cnNvciB0byBwaXBlbGluZSBJRGF0YSBvYmplY3QNCklEYXRhQ3Vyc29yIGlkY1Bp
cGVsaW5lID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCi8vIEluaXRpYWxpemUgdmFyaWFibGVz
DQpTdHJpbmcgc3RyTWVtb3J5S2V5ID0gbnVsbDsNCklEYXRhIGlkTWVtb3J5ID0gbnVsbDsNCg0K
Ly8gR2V0IGRhdGEgb3V0IG9mIHBpcGVsaW5lDQppZiAoaWRjUGlwZWxpbmUuZmlyc3QoIk1lbW9y
eUtleSIpKQ0Kew0KICBzdHJNZW1vcnlLZXkgPSAoU3RyaW5nKSBpZGNQaXBlbGluZS5nZXRWYWx1
ZSgpOw0KfQ0KZWxzZQ0Kew0KICAvLyBQcmludCB0byBzdGFuZGFyZCBvdXRwdXQgYW4gZXJyb3Ig
bWVzc2FnZSBhbmQgZXhpdCBwcm9jZXNzaW5nDQogIFN5c3RlbS5vdXQucHJpbnRsbigiU2Vydmlj
ZTogVXRpbC5tZW1vcnkucGVyc2lzdGVuY2U6Z2V0RGF0YUZyb21NZW1vcnkgfCAiICsgInJlcXVp
cmVkIHBhcmFtZXRlciAnTWVtb3J5S2V5JyBtaXNzaW5nIik7DQogIHJldHVybjsNCn0NCg0KaWRN
ZW1vcnkgPSAoSURhdGEpIE1lbW9yeS5nZXQoc3RyTWVtb3J5S2V5KTsNCmlmIChpZE1lbW9yeSA9
PSBudWxsKQ0Kew0KICAvLyBQcmludCB0byBzdGFuZGFyZCBvdXRwdXQgYW4gZXJyb3IgbWVzc2Fn
ZSBhbmQgZXhpdCBwcm9jZXNzaW5nDQogIFN5c3RlbS5vdXQucHJpbnRsbigiU2VydmljZTogVXRp
bC5tZW1vcnkucGVyc2lzdGVuY2U6Z2V0RGF0YUZyb21NZW1vcnkgfCAiICsgIlVuYWJsZSB0byBm
aW5kICdNZW1vcnlLZXknIDoiICsgc3RyTWVtb3J5S2V5ICsgIiBpbiBNZW1vcnkiKTsNCiAgcmV0
dXJuOw0KfQ0KDQovLyBQdXQgc2Vzc2lvbiBvYmplY3QgaW50byBwaXBlbGluZQ0KaWRjUGlwZWxp
bmUuaW5zZXJ0QWZ0ZXIoIk1lbW9yeURhdGEiLCBpZE1lbW9yeSk7DQoNCi8vIEFsd2F5cyBkZXN0
cm95IHlvdXIgY3Vyc29ycw0KaWRjUGlwZWxpbmUuZGVzdHJveSgpOw0K</value>
</Values>
