<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">formatNumber</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required number</value>
    <value>[i] field:0:optional integerDigits</value>
    <value>[i] field:0:optional minFractionDigits</value>
    <value>[i] field:0:optional maxFractionDigits</value>
    <value>[o] field:0:required formattedNumber</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCmRvdWJsZSBudW1i
ZXIgPSAwOw0KaW50IGludGVnZXJEaWdpdHMgPSAwOw0KaW50IG1pbkZyYWN0aW9uRGlnaXRzID0g
MDsNCmludCBtYXhGcmFjdGlvbkRpZ2l0cyA9IDA7DQoNCmlmIChjdXJzb3IuZmlyc3QoIm51bWJl
ciIpKQ0Kew0KICBTdHJpbmcgdGVtcCA9IChTdHJpbmcpIGN1cnNvci5nZXRWYWx1ZSgpOw0KICBp
ZiAodGVtcCAhPSBudWxsICYmIHRlbXAubGVuZ3RoKCkgPiAwKQ0KICB7DQogICAgbnVtYmVyID0g
RG91YmxlLnBhcnNlRG91YmxlKHRlbXApOw0KICB9DQp9DQoNCmludCBpbnRlZ2VyTGVuZ3RoID0g
U3RyaW5nLnZhbHVlT2YoKGxvbmcpIG51bWJlcikubGVuZ3RoKCk7DQppZiAoY3Vyc29yLmZpcnN0
KCJpbnRlZ2VyRGlnaXRzIikpDQp7DQogIFN0cmluZyB0ZW1wID0gKFN0cmluZykgY3Vyc29yLmdl
dFZhbHVlKCk7DQogIGlmICh0ZW1wICE9IG51bGwgJiYgdGVtcC5sZW5ndGgoKSA+IDApDQogIHsN
CiAgICBpbnRlZ2VyRGlnaXRzID0gSW50ZWdlci5wYXJzZUludCh0ZW1wKTsNCiAgfQ0KfQ0KDQpp
ZiAoY3Vyc29yLmZpcnN0KCJtaW5GcmFjdGlvbkRpZ2l0cyIpKQ0Kew0KICBTdHJpbmcgdGVtcCA9
IChTdHJpbmcpIGN1cnNvci5nZXRWYWx1ZSgpOw0KICBpZiAodGVtcCAhPSBudWxsICYmIHRlbXAu
bGVuZ3RoKCkgPiAwKQ0KICB7DQogICAgbWluRnJhY3Rpb25EaWdpdHMgPSBJbnRlZ2VyLnBhcnNl
SW50KHRlbXApOw0KICB9DQp9DQoNCmlmIChjdXJzb3IuZmlyc3QoIm1heEZyYWN0aW9uRGlnaXRz
IikpDQp7DQogIFN0cmluZyB0ZW1wID0gKFN0cmluZykgY3Vyc29yLmdldFZhbHVlKCk7DQogIGlm
ICh0ZW1wICE9IG51bGwgJiYgdGVtcC5sZW5ndGgoKSA+IDApDQogIHsNCiAgICBtYXhGcmFjdGlv
bkRpZ2l0cyA9IEludGVnZXIucGFyc2VJbnQodGVtcCk7DQogIH0NCn0NCg0KaWYgKG1heEZyYWN0
aW9uRGlnaXRzIDwgbWluRnJhY3Rpb25EaWdpdHMpDQp7DQogIG1heEZyYWN0aW9uRGlnaXRzID0g
bWluRnJhY3Rpb25EaWdpdHM7DQp9DQoNCk51bWJlckZvcm1hdCBuZm10ID0gTnVtYmVyRm9ybWF0
LmdldEluc3RhbmNlKCk7DQpuZm10LnNldE1pbmltdW1JbnRlZ2VyRGlnaXRzKGludGVnZXJEaWdp
dHMpOw0KbmZtdC5zZXRNYXhpbXVtSW50ZWdlckRpZ2l0cyhpbnRlZ2VyRGlnaXRzID4gaW50ZWdl
ckxlbmd0aCA/IGludGVnZXJEaWdpdHMgOiBpbnRlZ2VyTGVuZ3RoKTsNCm5mbXQuc2V0TWluaW11
bUZyYWN0aW9uRGlnaXRzKG1pbkZyYWN0aW9uRGlnaXRzKTsNCm5mbXQuc2V0TWF4aW11bUZyYWN0
aW9uRGlnaXRzKG1heEZyYWN0aW9uRGlnaXRzKTsNCm5mbXQuc2V0R3JvdXBpbmdVc2VkKGZhbHNl
KTsNCg0KaWYgKGN1cnNvci5maXJzdCgiZm9ybWF0dGVkTnVtYmVyIikpDQp7DQogIGN1cnNvci5z
ZXRWYWx1ZShuZm10LmZvcm1hdChudW1iZXIpKTsNCn0NCmVsc2UNCnsNCiAgY3Vyc29yLmluc2Vy
dEFmdGVyKCJmb3JtYXR0ZWROdW1iZXIiLCBuZm10LmZvcm1hdChudW1iZXIpKTsNCn0NCg0KY3Vy
c29yLmRlc3Ryb3koKTsNCg==</value>
</Values>
