<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getSystemProperties</value>
  <array name="sig" type="value" depth="1">
    <value>[o] field:2:required propertyList</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqDQogKiBTZXJ2aWNlIGlzIGRlc2lnbmVkIHRvIHJldHVybiBhIGxpc3Qgb2YgYWxsIGF2YWls
YWJsZSBzeXN0ZW0gcHJvcGVydGllcy4NCiAqIA0KICovDQoNCklEYXRhQ3Vyc29yIGlkYyA9IHBp
cGVsaW5lLmdldEN1cnNvcigpOw0KUHJvcGVydGllcyBwcm9wID0gU3lzdGVtLmdldFByb3BlcnRp
ZXMoKTsNCkVudW1lcmF0aW9uIHByb3BLZXlMaXN0ID0gcHJvcC5wcm9wZXJ0eU5hbWVzKCk7DQpW
ZWN0b3IgcHJvcFZlYyA9IG5ldyBWZWN0b3IoKTsNClZlY3RvciB2YWx1ZVZlYyA9IG5ldyBWZWN0
b3IoKTsNCg0Kb3V0ZXI6IHdoaWxlICh0cnVlKQ0Kew0KICBpZiAocHJvcEtleUxpc3QuaGFzTW9y
ZUVsZW1lbnRzKCkgPT0gdHJ1ZSkNCiAgew0KICAgIFN0cmluZyBlbGVtZW50TmFtZSA9IChTdHJp
bmcpIHByb3BLZXlMaXN0Lm5leHRFbGVtZW50KCk7DQogICAgU3RyaW5nIGVsZW1lbnRWYWx1ZSA9
IFN5c3RlbS5nZXRQcm9wZXJ0eShlbGVtZW50TmFtZSwgIk5vIHByb3BlcnR5IGZvdW5kIik7DQog
ICAgcHJvcFZlYy5hZGRFbGVtZW50KGVsZW1lbnROYW1lKTsNCiAgICB2YWx1ZVZlYy5hZGRFbGVt
ZW50KGVsZW1lbnRWYWx1ZSk7DQogIH0NCiAgZWxzZQ0KICAgIGJyZWFrIG91dGVyOw0KfQ0KDQpT
dHJpbmdbXSBhbGxQcm9wc0NvbEhlYWRlcnMgPSB7ICJLZXkiLCAiVmFsdWUiIH07DQpUYWJsZSBh
bGxQcm9wcyA9IG5ldyBUYWJsZShhbGxQcm9wc0NvbEhlYWRlcnMpOw0KZm9yIChpbnQgaSA9IDA7
IGkgPCBwcm9wVmVjLnNpemUoKTsgaSsrKQ0Kew0KICBTdHJpbmdbXSBpbmRpdmlkdWFsUm93cyA9
IHsgKFN0cmluZykgcHJvcFZlYy5lbGVtZW50QXQoaSksIChTdHJpbmcpIHZhbHVlVmVjLmVsZW1l
bnRBdChpKSB9Ow0KICBhbGxQcm9wcy5hZGRSb3coaW5kaXZpZHVhbFJvd3MpOw0KfQ0KDQppZiAo
aWRjLmZpcnN0KCJwcm9wZXJ0eUxpc3QiKSkNCiAgaWRjLmRlbGV0ZSgpOw0KDQppZGMuaW5zZXJ0
QWZ0ZXIoInByb3BlcnR5TGlzdCIsIGFsbFByb3BzKTsNCmlkYy5kZXN0cm95KCk7DQo=</value>
</Values>
