<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">runTContextJob</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required host</value>
    <value>[i] field:0:required port</value>
    <value>[i] field:0:required folder</value>
    <value>[i] field:0:required service</value>
    <value>[i] field:0:required username</value>
    <value>[i] field:0:required password</value>
    <value>[i] field:0:required ttl</value>
    <value>[i] field:0:required retries</value>
    <value>[i] field:0:required useSSL {"false","true"}</value>
    <value>[i] field:0:required privKeyFile</value>
    <value>[i] field:1:required certFiles</value>
    <value>[i] field:0:optional async? {"true","false"}</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRjUGlwZWxpbmUgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCg0KaW50IHR0
bCA9IDA7IC8vIGlmIDAgaXMgdXNlZCwgZGVmYXVsdCB0dGwgaXMgdXNlZA0KaW50IHJldHJpZXMg
PSAwOw0KDQpTdHJpbmcgaG9zdCA9ICIiOw0KU3RyaW5nIHBvcnQgPSAiIjsNClN0cmluZyBmb2xk
ZXJOYW1lID0gIiI7DQpTdHJpbmcgc2VydmljZU5hbWUgPSAiIjsNCmlmIChpZGNQaXBlbGluZS5m
aXJzdCgiaG9zdCIpKQ0Kew0KICBob3N0ID0gKFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0VmFsdWUo
KTsNCn0NCmlmIChpZGNQaXBlbGluZS5maXJzdCgicG9ydCIpKQ0Kew0KICBwb3J0ID0gKFN0cmlu
ZykgaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsNCn0NCmlmIChpZGNQaXBlbGluZS5maXJzdCgiZm9s
ZGVyIikpDQp7DQogIGZvbGRlck5hbWUgPSAoU3RyaW5nKSBpZGNQaXBlbGluZS5nZXRWYWx1ZSgp
Ow0KfQ0KZWxzZQ0Kew0KICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiRm9sZGVyIGNhbm5v
dCBiZSBudWxsISIpOw0KfQ0KaWYgKGlkY1BpcGVsaW5lLmZpcnN0KCJzZXJ2aWNlIikpDQp7DQog
IHNlcnZpY2VOYW1lID0gKFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsNCn0NCmVsc2UN
CnsNCiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIlNlcnZpY2UgY2Fubm90IGJlIG51bGwh
Iik7DQp9DQoNCmlkY1BpcGVsaW5lLmZpcnN0KCJ1c2VybmFtZSIpOw0KU3RyaW5nIHVzZXJuYW1l
ID0gKFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsNCmlkY1BpcGVsaW5lLmZpcnN0KCJw
YXNzd29yZCIpOw0KU3RyaW5nIHBhc3N3b3JkID0gKFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0VmFs
dWUoKTsNCg0KaWRjUGlwZWxpbmUuZmlyc3QoInVzZVNTTCIpOw0KU3RyaW5nIHVzZVNTTCA9IChT
dHJpbmcpIGlkY1BpcGVsaW5lLmdldFZhbHVlKCk7DQppZGNQaXBlbGluZS5maXJzdCgicHJpdktl
eUZpbGUiKTsNClN0cmluZyBwcml2S2V5RmlsZSA9IChTdHJpbmcpIGlkY1BpcGVsaW5lLmdldFZh
bHVlKCk7DQpTdHJpbmcgY2VydEZpbGVzW10gPSBudWxsOw0KaWYgKGlkY1BpcGVsaW5lLmZpcnN0
KCJjZXJ0RmlsZXMiKSkNCiAgY2VydEZpbGVzID0gKFN0cmluZ1tdKSBpZGNQaXBlbGluZS5nZXRW
YWx1ZSgpOw0KaWRjUGlwZWxpbmUuZmlyc3QoImFzeW5jPyIpOw0KU3RyaW5nIGFzeW5jID0gKFN0
cmluZykgaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsNCg0KaWYgKGlkY1BpcGVsaW5lLmZpcnN0KCJ0
dGwiKSkNCnsNCiAgU3RyaW5nIFRUTCA9IChTdHJpbmcpIGlkY1BpcGVsaW5lLmdldFZhbHVlKCk7
DQogIHR0bCA9IEludGVnZXIucGFyc2VJbnQoVFRMKTsNCn0NCmlmIChpZGNQaXBlbGluZS5maXJz
dCgicmV0cmllcyIpKQ0Kew0KICBTdHJpbmcgUmV0cmllcyA9IChTdHJpbmcpIGlkY1BpcGVsaW5l
LmdldFZhbHVlKCk7DQogIHJldHJpZXMgPSBJbnRlZ2VyLnBhcnNlSW50KFJldHJpZXMpOw0KfQ0K
DQppZGNQaXBlbGluZS5kZXN0cm95KCk7DQoNCi8vIC0tLUluaXRpYWxpemF0aW9uLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KdHJ5DQp7DQogIFN0
cmluZyBVUkwgPSAiIjsNCiAgU2VydmVyQVBJIGFwaSA9IG5ldyBTZXJ2ZXJBUEkoKTsNCiAgaWYg
KGhvc3QgPT0gbnVsbCkNCiAgICBob3N0ID0gYXBpLmdldFNlcnZlck5hbWUoKTsNCiAgaWYgKHBv
cnQgPT0gbnVsbCkNCiAgICBwb3J0ID0gSW50ZWdlci50b1N0cmluZyhhcGkuZ2V0Q3VycmVudFBv
cnQoKSk7DQoNCiAgaWYgKHBvcnQuZXF1YWxzKCItMSIpKQ0KICAgIFVSTCA9IGhvc3Q7DQogIGVs
c2UNCiAgICBVUkwgPSBob3N0ICsgIjoiICsgcG9ydDsNCg0KICAvLyBUQ29udGV4dCBpbml0aWFs
aXphdGlvbg0KICBUQ29udGV4dCB0eCA9IG5ldyBUQ29udGV4dCgpOw0KICBpZiAodXNlU1NMLmVx
dWFscygidHJ1ZSIpKQ0KICB7DQogICAgdHguc2V0U2VjdXJlKHRydWUpOw0KICB9DQoNCiAgaWYg
KChwcml2S2V5RmlsZSAhPSBudWxsKSAmJiAoY2VydEZpbGVzICE9IG51bGwpKQ0KICB7DQogICAg
dHguc2V0U1NMQ2VydGlmaWNhdGVzKHByaXZLZXlGaWxlLCBjZXJ0RmlsZXMpOw0KICB9DQoNCiAg
dHguY29ubmVjdChVUkwsIHVzZXJuYW1lLCBwYXNzd29yZCk7DQoNCiAgLy8gc3RhcnQgdHJhbnNh
Y3Rpb24NCiAgU3RyaW5nIHRpZCA9IHR4LnN0YXJ0VHgodHRsLCByZXRyaWVzKTsNCiAgaWYgKGFz
eW5jLmVxdWFsc0lnbm9yZUNhc2UoInRydWUiKSkNCiAgew0KICAgIHR4LnN1Ym1pdFR4KHRpZCwg
Zm9sZGVyTmFtZSwgc2VydmljZU5hbWUsIHBpcGVsaW5lKTsNCiAgfQ0KICBlbHNlDQogIHsNCiAg
ICBJRGF0YSByZXN1bHRzID0gdHguaW52b2tlVHgodGlkLCBmb2xkZXJOYW1lLCBzZXJ2aWNlTmFt
ZSwgcGlwZWxpbmUpOw0KICAgIElEYXRhVXRpbC5tZXJnZShyZXN1bHRzLCBwaXBlbGluZSk7DQoN
CiAgfQ0KDQogIHR4LmVuZFR4KHRpZCk7DQoNCiAgdHguZGlzY29ubmVjdCgpOw0KDQp9DQpjYXRj
aCAoRXhjZXB0aW9uIGUpDQp7DQogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUpOw0KfQ0K
DQo=</value>
</Values>
