<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">spawnThread</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required serviceName</value>
    <value>[i] record:0:required input</value>
    <value>[o] object:0:required threadHandle</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">DQpJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KSURhdGEg
aW5wdXQgPSBudWxsOw0KU3RyaW5nIHNlcnZpY2VOYW1lID0gbnVsbDsNCmlmIChpZGNQaXBlbGlu
ZS5maXJzdCgic2VydmljZU5hbWUiKSkNCnsNCiAgc2VydmljZU5hbWUgPSAoU3RyaW5nKSBpZGNQ
aXBlbGluZS5nZXRWYWx1ZSgpOw0KfQ0KZWxzZQ0Kew0KICB0aHJvdyBuZXcgU2VydmljZUV4Y2Vw
dGlvbigic2VydmljZSBjYW5ub3QgYmUgbnVsbCIpOw0KfQ0KDQppZiAoaWRjUGlwZWxpbmUuZmly
c3QoImlucHV0IikpDQp7DQogIGlucHV0ID0gKElEYXRhKSBpZGNQaXBlbGluZS5nZXRWYWx1ZSgp
Ow0KfQ0KDQovLyAqKiogQ2hlY2sgaWYgc2VydmljZSBpcyBvbiB0aGUgYWxsb3dlZCBsaXN0ICoq
Kg0KSURhdGEgaW4gPSBJRGF0YUZhY3RvcnkuY3JlYXRlKCk7DQpJRGF0YUN1cnNvciBpZGNJbiA9
IGluLmdldEN1cnNvcigpOw0KaWRjSW4uaW5zZXJ0QWZ0ZXIoInBhcmFtTmFtZSIsICJhbGxvd2Vk
U2VydmljZXMiKTsNCmlkY0luLmluc2VydEFmdGVyKCJwYXJhbVZhbHVlIiwgc2VydmljZU5hbWUp
Ow0KTlNOYW1lIG5zQ2hlY2tTZXJ2aWNlTmFtZSA9IE5TTmFtZS5jcmVhdGUoIlBTVXRpbGl0aWVz
LmNvbmZpZzpjaGVja1BhcmFtZXRlclZhbGlkaXR5Iik7DQppZGNJbi5kZXN0cm95KCk7DQpJRGF0
YSBvdXQ7DQp0cnkNCnsNCiAgb3V0ID0gU2VydmljZS5kb0ludm9rZShuc0NoZWNrU2VydmljZU5h
bWUsIGluKTsNCn0NCmNhdGNoIChFeGNlcHRpb24gZSkNCnsNCiAgdGhyb3cgbmV3IFNlcnZpY2VF
eGNlcHRpb24oZS5nZXRNZXNzYWdlKCkpOw0KfQ0KSURhdGFDdXJzb3IgaWRjT3V0ID0gb3V0Lmdl
dEN1cnNvcigpOw0KU3RyaW5nIHN0clZhbGlkID0gbnVsbDsNCmlmIChpZGNPdXQuZmlyc3QoInZh
bGlkIikpDQp7DQogIHN0clZhbGlkID0gKFN0cmluZykgaWRjT3V0LmdldFZhbHVlKCk7DQp9DQpp
ZGNPdXQuZGVzdHJveSgpOw0KDQppZiAoc3RyVmFsaWQuZXF1YWxzKCJmYWxzZSIpKQ0Kew0KICB0
aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiU3BlY2lmaWVkIHNlcnZpY2UgaXMgbm90IG9uIHRo
ZSBhbGxvd2VkIGxpc3QgaW4gdGhlIFBTVXRpbGl0aWVzIGNvbmZpZ3VyYXRpb24gZmlsZSEiKTsN
Cn0NCi8vICoqKiBFbmQgY2hlY2sgKioqDQoNCnRyeQ0Kew0KICAvLyBTcGxpdCB0aGUgaW50ZXJm
YWNlIGFuZCBzZXJ2aWNlIGZyb20gc2VydmljZU5hbWUNCiAgaWYgKHNlcnZpY2VOYW1lLmluZGV4
T2YoIjoiKSA9PSAtMSkNCiAgew0KICAgIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJTZXJ2
aWNlIG5hbWUgbXVzdCBiZSBpbiB0aGUgZm9ybWF0IDxpbnRlcmZhY2U+OjxzZXJ2aWNlPiIpOw0K
ICB9DQogIFN0cmluZyBpZmMgPSBzZXJ2aWNlTmFtZS5zdWJzdHJpbmcoMCwgc2VydmljZU5hbWUu
aW5kZXhPZigiOiIpKTsNCiAgU3RyaW5nIHNlcnZpY2UgPSBzZXJ2aWNlTmFtZS5zdWJzdHJpbmco
c2VydmljZU5hbWUuaW5kZXhPZigiOiIpICsgMSwgc2VydmljZU5hbWUubGVuZ3RoKCkpOw0KDQog
IC8vIEludm9rZSBzZXJ2aWNlDQogIFNlcnZpY2VUaHJlYWQgdGhyZWFkSGFuZGxlID0gU2Vydmlj
ZS5kb1RocmVhZEludm9rZShpZmMsIHNlcnZpY2UsIElEYXRhVXRpbC5kZWVwQ2xvbmUoaW5wdXQp
KTsNCiAgaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInRocmVhZEhhbmRsZSIsIHRocmVhZEhhbmRs
ZSk7DQp9DQpjYXRjaCAoRXhjZXB0aW9uIGUpDQp7DQogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0
aW9uKGUuZ2V0TWVzc2FnZSgpKTsNCn0NCmZpbmFsbHkNCnsNCiAgaWRjUGlwZWxpbmUuZGVzdHJv
eSgpOw0KfQ0K</value>
</Values>
