<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">deepConvert</value>
  <array name="sig" type="value" depth="1">
    <value>[i] object:0:required hashtable</value>
    <value>[o] record:0:required convertedValues</value>
  </array>
  <value name="sigtype">java 3.0</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqDQogKiBUaGlzIG1ldGhvZCB3aWxsIGRlZXAgY29udmVydCBhIEhhc2h0YWJsZSB0byBhIFZh
bHVlcyBvYmplY3QuIFRoYXQgaXMsIGl0DQogKiB3aWxsIGJlIGRlc2lnbmVkIHRvIGNvbnZlcnQg
YWxsIEhhc2h0YWJsZSBvYmplY3RzIHdpdGhpbiBhIGhhc2h0YWJsZSwNCiAqIG5lc3RlZCBvciBu
b3QsIHRvIGEgdmFsdWVzIG9iamVjdC4NCiAqIA0KICovDQoNCi8vIEdldCB0aGUgaW5ib3VuZCBI
YXNodGFibGUgb2JqZWN0Lg0KSGFzaHRhYmxlIGhUID0gKEhhc2h0YWJsZSkgaW4uZ2V0KCJoYXNo
dGFibGUiKTsNCg0KYm9vbGVhbiBudWxsRmxhZyA9IGZhbHNlOw0KVmFsdWVzIG91dGJvdW5kID0g
bmV3IFZhbHVlcygpOw0KdHJ5DQp7DQogIC8vIEZvbGxvd2luZyBzdGF0ZW1lbnQgZ2V0cyBhbGwg
YXJyYXlzIGluIHRoaXMgb2JqZWN0Lg0KICBPYmplY3RbXSBoVEFycmF5ID0gaFQudmFsdWVzKCku
dG9BcnJheSgpOw0KICBFbnVtZXJhdGlvbiBoVEVudW1lcmF0aW9uID0gaFQua2V5cygpOw0KDQog
IGZvciAoaW50IGkgPSAwOyBpIDwgaFRBcnJheS5sZW5ndGg7IGkrKykNCiAgew0KICAgIFN0cmlu
ZyBrZXkgPSAoU3RyaW5nKSBoVEVudW1lcmF0aW9uLm5leHRFbGVtZW50KCk7DQogICAgaWYgKGhU
QXJyYXlbaV0gaW5zdGFuY2VvZiBqYXZhLmxhbmcuU3RyaW5nKQ0KICAgIHsNCiAgICAgIG91dGJv
dW5kLnB1dChrZXksIChTdHJpbmcpIGhUQXJyYXlbaV0pOw0KICAgIH0NCiAgICBlbHNlIGlmICho
VEFycmF5W2ldIGluc3RhbmNlb2YgamF2YS51dGlsLkhhc2h0YWJsZSkNCiAgICB7DQogICAgICBW
YWx1ZXMgaW50ZXJuYWxPYmplY3QgPSBjb252ZXJ0KChIYXNodGFibGUpIGhUQXJyYXlbaV0pOw0K
ICAgICAgaWYgKGludGVybmFsT2JqZWN0ID09IG51bGwpDQogICAgICB7DQogICAgICAgIG51bGxG
bGFnID0gdHJ1ZTsNCiAgICAgICAgb3V0LnB1dCgiY29udmVydGVkVmFsdWVzIiwgbnVsbCk7DQog
ICAgICAgIHJldHVybiBvdXQ7DQogICAgICB9DQogICAgICBvdXRib3VuZC5wdXQoa2V5LCBpbnRl
cm5hbE9iamVjdCk7DQogICAgfQ0KICAgIGVsc2UNCiAgICB7DQogICAgICBTeXN0ZW0ub3V0LnBy
aW50bG4oIkNvbnZlcnNpb24gRmFpbHVyZToiICsgInVuc3VwcG9ydGVkIHR5cGUgd2l0aGluIGlu
Ym91bmQgSGFzaHRhYmxlLiIpOw0KICAgICAgb3V0LnB1dCgiY29udmVydGVkVmFsdWVzIiwgbnVs
bCk7DQogICAgICByZXR1cm4gb3V0Ow0KICAgIH0NCiAgfQ0KfQ0KY2F0Y2ggKGphdmEubGFuZy5F
eGNlcHRpb24gZXgpDQp7DQogIFN5c3RlbS5vdXQucHJpbnRsbigiQ29udmVyc2lvbiBGYWlsdXJl
OiIgKyBleC5nZXRNZXNzYWdlKCkpOw0KICBvdXQucHV0KCJjb252ZXJ0ZWRWYWx1ZXMiLCBudWxs
KTsNCiAgcmV0dXJuIG91dDsNCn0NCm91dC5wdXQoImNvbnZlcnRlZFZhbHVlcyIsIG91dGJvdW5k
KTsNCg==</value>
</Values>
