<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">spawnThread2</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required serviceName</value>
    <value>[o] object:0:required threadHandle</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">DQpJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KU3RyaW5n
IHNlcnZpY2VOYW1lID0gbnVsbDsNCmlmIChpZGNQaXBlbGluZS5maXJzdCgic2VydmljZU5hbWUi
KSkNCnsNCiAgc2VydmljZU5hbWUgPSAoU3RyaW5nKSBpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOw0K
fQ0KZWxzZQ0Kew0KICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigic2VydmljZSBjYW5ub3Qg
YmUgbnVsbCIpOw0KfQ0KDQovLyAqKiogQ2hlY2sgaWYgc2VydmljZSBpcyBvbiB0aGUgYWxsb3dl
ZCBsaXN0ICoqKg0KSURhdGEgaW4gPSBJRGF0YUZhY3RvcnkuY3JlYXRlKCk7DQpJRGF0YUN1cnNv
ciBpZGNJbiA9IGluLmdldEN1cnNvcigpOw0KaWRjSW4uaW5zZXJ0QWZ0ZXIoInBhcmFtTmFtZSIs
ICJhbGxvd2VkU2VydmljZXMiKTsNCmlkY0luLmluc2VydEFmdGVyKCJwYXJhbVZhbHVlIiwgc2Vy
dmljZU5hbWUpOw0KTlNOYW1lIG5zQ2hlY2tTZXJ2aWNlTmFtZSA9IE5TTmFtZS5jcmVhdGUoIlBT
VXRpbGl0aWVzLmNvbmZpZzpjaGVja1BhcmFtZXRlclZhbGlkaXR5Iik7DQppZGNJbi5kZXN0cm95
KCk7DQpJRGF0YSBvdXQ7DQp0cnkNCnsNCiAgb3V0ID0gU2VydmljZS5kb0ludm9rZShuc0NoZWNr
U2VydmljZU5hbWUsIGluKTsNCn0NCmNhdGNoIChFeGNlcHRpb24gZSkNCnsNCiAgdGhyb3cgbmV3
IFNlcnZpY2VFeGNlcHRpb24oZS5nZXRNZXNzYWdlKCkpOw0KfQ0KSURhdGFDdXJzb3IgaWRjT3V0
ID0gb3V0LmdldEN1cnNvcigpOw0KU3RyaW5nIHN0clZhbGlkID0gbnVsbDsNCmlmIChpZGNPdXQu
Zmlyc3QoInZhbGlkIikpDQp7DQogIHN0clZhbGlkID0gKFN0cmluZykgaWRjT3V0LmdldFZhbHVl
KCk7DQp9DQppZGNPdXQuZGVzdHJveSgpOw0KDQppZiAoc3RyVmFsaWQuZXF1YWxzKCJmYWxzZSIp
KQ0Kew0KICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiU3BlY2lmaWVkIHNlcnZpY2UgaXMg
bm90IG9uIHRoZSBhbGxvd2VkIGxpc3QgaW4gdGhlIFBTVXRpbGl0aWVzIGNvbmZpZ3VyYXRpb24g
ZmlsZSEiKTsNCn0NCi8vICoqKiBFbmQgY2hlY2sgKioqDQoNCnRyeQ0Kew0KICAvLyBTcGxpdCB0
aGUgaW50ZXJmYWNlIGFuZCBzZXJ2aWNlIGZyb20gc2VydmljZU5hbWUNCiAgaWYgKHNlcnZpY2VO
YW1lLmluZGV4T2YoIjoiKSA9PSAtMSkNCiAgew0KICAgIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0
aW9uKCJTZXJ2aWNlIG5hbWUgbXVzdCBiZSBpbiB0aGUgZm9ybWF0IDxpbnRlcmZhY2U+OjxzZXJ2
aWNlPiIpOw0KICB9DQogIFN0cmluZyBpZmMgPSBzZXJ2aWNlTmFtZS5zdWJzdHJpbmcoMCwgc2Vy
dmljZU5hbWUuaW5kZXhPZigiOiIpKTsNCiAgU3RyaW5nIHNlcnZpY2UgPSBzZXJ2aWNlTmFtZS5z
dWJzdHJpbmcoc2VydmljZU5hbWUuaW5kZXhPZigiOiIpICsgMSwgc2VydmljZU5hbWUubGVuZ3Ro
KCkpOw0KDQogIC8vIEludm9rZSBzZXJ2aWNlDQogIFNlcnZpY2VUaHJlYWQgdGhyZWFkSGFuZGxl
ID0gU2VydmljZS5kb1RocmVhZEludm9rZShpZmMsIHNlcnZpY2UsIElEYXRhVXRpbC5kZWVwQ2xv
bmUocGlwZWxpbmUpKTsNCiAgaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInRocmVhZEhhbmRsZSIs
IHRocmVhZEhhbmRsZSk7DQp9DQpjYXRjaCAoRXhjZXB0aW9uIGUpDQp7DQogIHRocm93IG5ldyBT
ZXJ2aWNlRXhjZXB0aW9uKGUuZ2V0TWVzc2FnZSgpKTsNCn0NCmZpbmFsbHkNCnsNCiAgaWRjUGlw
ZWxpbmUuZGVzdHJveSgpOw0KfQ0K</value>
</Values>
