<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">concatFields</value>
  <array name="sig" type="value" depth="1">
    <value>[i] record:0:required inRecord</value>
    <value>[i] field:1:optional sortOrder</value>
    <value>[i] field:0:optional separator</value>
    <value>[i] field:0:optional skipNulls {"false","true"}</value>
    <value>[o] field:0:required value</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNClN0cmluZ0J1ZmZl
ciBidWZmZXIgPSBuZXcgU3RyaW5nQnVmZmVyKCk7DQpTdHJpbmcgc2VwYXJhdG9yID0gbnVsbDsN
ClN0cmluZ1tdIHNvcnRPcmRlciA9IG51bGw7DQpib29sZWFuIHNraXBOdWxscyA9IElEYXRhVXRp
bC5nZXRCb29sZWFuKGN1cnNvciwgInNraXBOdWxscyIsIGZhbHNlKTsNCg0KaWYgKGN1cnNvci5m
aXJzdCgic2VwYXJhdG9yIikpDQp7DQogIHNlcGFyYXRvciA9IChTdHJpbmcpIGN1cnNvci5nZXRW
YWx1ZSgpOw0KfQ0KDQppZiAoY3Vyc29yLmZpcnN0KCJzb3J0T3JkZXIiKSkNCnsNCiAgc29ydE9y
ZGVyID0gKFN0cmluZ1tdKSBjdXJzb3IuZ2V0VmFsdWUoKTsNCn0NCg0KSURhdGEgaW5SZWNvcmQg
PSBJRGF0YVV0aWwuZ2V0SURhdGEoY3Vyc29yLCAiaW5SZWNvcmQiKTsNCmlmIChpblJlY29yZCA9
PSBudWxsKQ0Kew0KICBpblJlY29yZCA9IElEYXRhRmFjdG9yeS5jcmVhdGUoKTsNCn0NCg0KSURh
dGFDdXJzb3IgaW5SZWNvcmRDdXJzb3IgPSBpblJlY29yZC5nZXRDdXJzb3IoKTsNCi8vIElmIG5v
IHNvcnRPcmRlciBpcyBzcGVjaWZpZWQsIGp1c3QgY29uY2F0ZW5hdGUgdGhlIGZpZWxkcyBiYXNl
ZCBvbiB0aGUNCi8vIGRlZmF1bHQgb3JkZXINCmlmIChzb3J0T3JkZXIgPT0gbnVsbCB8fCBzb3J0
T3JkZXIubGVuZ3RoID09IDApDQp7DQogIGJvb2xlYW4gZmlyc3RGaWVsZCA9IHRydWU7DQogIGZv
ciAoaW50IGkgPSAwOyBpblJlY29yZEN1cnNvci5uZXh0KCk7IGkrKykNCiAgew0KICAgIFN0cmlu
ZyB2YWx1ZSA9IChTdHJpbmcpIGluUmVjb3JkQ3Vyc29yLmdldFZhbHVlKCk7DQogICAgaWYgKHZh
bHVlID09IG51bGwpDQogICAgew0KICAgICAgdmFsdWUgPSAiIjsNCiAgICB9DQoNCiAgICBpZiAo
c2tpcE51bGxzICYmICh2YWx1ZSA9PSBudWxsIHx8IHZhbHVlLmxlbmd0aCgpID09IDApKQ0KICAg
IHsNCiAgICAgIGNvbnRpbnVlOw0KICAgIH0NCg0KICAgIGlmICghZmlyc3RGaWVsZCAmJiBzZXBh
cmF0b3IgIT0gbnVsbCkNCiAgICB7DQogICAgICBidWZmZXIuYXBwZW5kKHNlcGFyYXRvcik7DQog
ICAgfQ0KDQogICAgYnVmZmVyLmFwcGVuZCh2YWx1ZSk7DQogICAgZmlyc3RGaWVsZCA9IGZhbHNl
Ow0KICB9DQp9DQplbHNlDQp7DQogIC8vIFdoZW4gc29ydE9yZGVyIGlzIHNwZWNpZmllZCwgdXNl
IHRoYXQgdG8gcmV0cmlldmUgYW5kIGNvbmNhdGVuYXRlDQogIC8vIGZpZWxkcy4NCiAgYm9vbGVh
biBmaXJzdEZpZWxkID0gdHJ1ZTsNCiAgZm9yIChpbnQgaSA9IDA7IGkgPCBzb3J0T3JkZXIubGVu
Z3RoOyBpKyspDQogIHsNCiAgICBTdHJpbmcgdmFsdWUgPSAiIjsNCiAgICBpZiAoaW5SZWNvcmRD
dXJzb3IuZmlyc3Qoc29ydE9yZGVyW2ldKSkNCiAgICB7DQogICAgICB2YWx1ZSA9IChTdHJpbmcp
IGluUmVjb3JkQ3Vyc29yLmdldFZhbHVlKCk7DQogICAgICBpZiAodmFsdWUgPT0gbnVsbCkNCiAg
ICAgIHsNCiAgICAgICAgdmFsdWUgPSAiIjsNCiAgICAgIH0NCiAgICB9DQoNCiAgICBpZiAoc2tp
cE51bGxzICYmICh2YWx1ZSA9PSBudWxsIHx8IHZhbHVlLmxlbmd0aCgpID09IDApKQ0KICAgIHsN
CiAgICAgIGNvbnRpbnVlOw0KICAgIH0NCg0KICAgIGlmICghZmlyc3RGaWVsZCAmJiBzZXBhcmF0
b3IgIT0gbnVsbCkNCiAgICB7DQogICAgICBidWZmZXIuYXBwZW5kKHNlcGFyYXRvcik7DQogICAg
fQ0KDQogICAgYnVmZmVyLmFwcGVuZCh2YWx1ZSk7DQogICAgZmlyc3RGaWVsZCA9IGZhbHNlOw0K
ICB9DQp9DQoNCmlmIChidWZmZXIubGVuZ3RoKCkgPiAwKQ0Kew0KICBJRGF0YVV0aWwucHV0KGN1
cnNvciwgInZhbHVlIiwgYnVmZmVyLnRvU3RyaW5nKCkpOw0KfQ0KDQpjdXJzb3IuZGVzdHJveSgp
Ow0K</value>
</Values>
