<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">listFiles</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required directory</value>
    <value>[i] field:0:optional filter</value>
    <value>[o] field:1:required fileList</value>
    <value>[o] field:1:required fileList_fullpathnames</value>
    <value>[o] field:0:required numFiles</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRjUGlwZWxpbmUgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCg0KU3RyaW5n
IGZpbHRlclN0cmluZyA9IG51bGw7DQppZiAoaWRjUGlwZWxpbmUuZmlyc3QoImZpbHRlciIpKQ0K
ew0KICBmaWx0ZXJTdHJpbmcgPSAoU3RyaW5nKSBpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOw0KfQ0K
DQpTdHJpbmcgZGlyZWN0b3J5ID0gbnVsbDsNCmlmIChpZGNQaXBlbGluZS5maXJzdCgiZGlyZWN0
b3J5IikpDQp7DQogIGRpcmVjdG9yeSA9IChTdHJpbmcpIGlkY1BpcGVsaW5lLmdldFZhbHVlKCk7
DQp9DQplbHNlDQp7DQogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJEaXJlY3RvcnkgaXMg
bnVsbCEiKTsNCn0NCg0KU3RyaW5nIHN0ckZpbGVTZXBhcmF0b3IgPSBTeXN0ZW0uZ2V0UHJvcGVy
dHkoImZpbGUuc2VwYXJhdG9yIik7DQppbnQgbnVtRmlsZXMgPSAwOw0KDQovLyAqKiogQ2hlY2sg
aWYgcGF0aCBpcyBvbiB0aGUgYWxsb3dlZCBsaXN0ICoqKg0KdHJ5DQp7DQogIGlmICghY2hlY2tQ
YXRoVmFsaWRpdHkoZGlyZWN0b3J5LCAicmVhZCIpKQ0KICB7DQogICAgdGhyb3cgbmV3IFNlcnZp
Y2VFeGNlcHRpb24oIlNwZWNpZmllZCBwYXRoIGlzIG5vdCBvbiB0aGUgcmVhZCBhbGxvd2VkIGxp
c3QgaW4gdGhlIFBTVXRpbGl0aWVzIGNvbmZpZ3VyYXRpb24gZmlsZSEiKTsNCiAgfQ0KfQ0KY2F0
Y2ggKEV4Y2VwdGlvbiBlKQ0Kew0KICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlLmdldE1l
c3NhZ2UoKSk7DQp9DQovLyAqKiogRW5kIGNoZWNrICoqKg0KDQpGaWxlIGRpciA9IG5ldyBGaWxl
KGRpcmVjdG9yeSk7DQoNCmlmICghZGlyLmV4aXN0cygpIHx8ICFkaXIuaXNEaXJlY3RvcnkoKSkN
CnsNCiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIkVycm9yIHJlYWRpbmcgaW5ib3ggZGly
ZWN0b3J5ISIpOw0KfQ0KDQpTdHJpbmcgZGlyX2xpc3RbXTsNCmlmICgoZmlsdGVyU3RyaW5nICE9
IG51bGwpICYmIGZpbHRlclN0cmluZy5sZW5ndGgoKSA+IDApDQp7DQogIEpaT09XaWxkQ2FyZEZp
bHRlciBmaWx0ZXIgPSBuZXcgSlpPT1dpbGRDYXJkRmlsdGVyKGZpbHRlclN0cmluZyk7DQogIGRp
cl9saXN0ID0gZGlyLmxpc3QoZmlsdGVyKTsNCn0NCmVsc2UNCnsNCiAgZGlyX2xpc3QgPSBkaXIu
bGlzdCgpOw0KfQ0KaW50IG51bV9maWxlc2FuZGRpciA9IGRpcl9saXN0Lmxlbmd0aDsNCg0KaWYg
KG51bV9maWxlc2FuZGRpciA8IDEpIC8vIE5vIGZpbGVzIHRvIHNlbmQNCnsNCiAgaWRjUGlwZWxp
bmUuaW5zZXJ0QWZ0ZXIoIm51bUZpbGVzIiwgSW50ZWdlci50b1N0cmluZyhudW1GaWxlcykpOw0K
ICByZXR1cm47DQp9DQoNCi8vIERldGVybWluZSBudW1iZXIgb2YgYWN0dWFsIGZpbGVzDQpGaWxl
IGN1cnJfZmlsZTsNCmZvciAoaW50IGkgPSAwOyBpIDwgbnVtX2ZpbGVzYW5kZGlyOyBpKyspDQp7
DQogIGN1cnJfZmlsZSA9IG5ldyBGaWxlKGRpcmVjdG9yeSArIHN0ckZpbGVTZXBhcmF0b3IgKyBk
aXJfbGlzdFtpXSk7DQogIGlmIChjdXJyX2ZpbGUuaXNGaWxlKCkpDQogIHsNCiAgICBudW1GaWxl
cysrOw0KICB9DQp9DQpjdXJyX2ZpbGUgPSBudWxsOw0KDQovLyBDcmVhdGUgYXJyYXkgd2l0aCBv
bmx5IG5hbWVzIG9mIGZpbGVzIChleGNsdWRpbmcgZGlyZWN0b3JpZXMpDQpTdHJpbmdbXSBmaWxl
TGlzdCA9IG5ldyBTdHJpbmdbbnVtRmlsZXNdOw0KU3RyaW5nW10gZmlsZUxpc3RfZnVsbHBhdGhu
YW1lcyA9IG5ldyBTdHJpbmdbbnVtRmlsZXNdOw0KbnVtRmlsZXMgPSAwOw0KZm9yIChpbnQgaSA9
IDA7IGkgPCBudW1fZmlsZXNhbmRkaXI7IGkrKykNCnsNCiAgY3Vycl9maWxlID0gbmV3IEZpbGUo
ZGlyZWN0b3J5ICsgc3RyRmlsZVNlcGFyYXRvciArIGRpcl9saXN0W2ldKTsNCiAgaWYgKGN1cnJf
ZmlsZS5pc0ZpbGUoKSkNCiAgew0KICAgIGZpbGVMaXN0W251bUZpbGVzXSA9IGRpcl9saXN0W2ld
Ow0KDQogICAgLy8gQXNzZW1ibGUgZnVsbHkgcXVhbGlmaWVkIGZpbGVuYW1lcyAoY2hlY2sgVU5J
WCAmIE5UKQ0KICAgIGNoYXIgbGFzdENoYXIgPSBkaXJlY3RvcnkuY2hhckF0KGRpcmVjdG9yeS5s
ZW5ndGgoKSAtIDEpOw0KICAgIGlmICgobGFzdENoYXIgPT0gJ1xcJykgfHwgKGxhc3RDaGFyID09
ICcvJykpDQogICAgew0KICAgICAgZmlsZUxpc3RfZnVsbHBhdGhuYW1lc1tudW1GaWxlc10gPSBk
aXJlY3RvcnkgKyBkaXJfbGlzdFtpXTsNCiAgICB9DQogICAgZWxzZQ0KICAgIHsNCiAgICAgIGZp
bGVMaXN0X2Z1bGxwYXRobmFtZXNbbnVtRmlsZXNdID0gZGlyZWN0b3J5ICsgc3RyRmlsZVNlcGFy
YXRvciArIGRpcl9saXN0W2ldOw0KICAgIH0NCiAgICBudW1GaWxlcysrOw0KICB9DQp9DQpjdXJy
X2ZpbGUgPSBudWxsOw0KDQppZGNQaXBlbGluZS5pbnNlcnRBZnRlcigibnVtRmlsZXMiLCBJbnRl
Z2VyLnRvU3RyaW5nKG51bUZpbGVzKSk7DQppZGNQaXBlbGluZS5pbnNlcnRBZnRlcigiZmlsZUxp
c3QiLCBmaWxlTGlzdCk7DQppZGNQaXBlbGluZS5pbnNlcnRBZnRlcigiZmlsZUxpc3RfZnVsbHBh
dGhuYW1lcyIsIGZpbGVMaXN0X2Z1bGxwYXRobmFtZXMpOw0KaWRjUGlwZWxpbmUuZGVzdHJveSgp
Ow0K</value>
</Values>
