<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">executeOSCommand</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required command</value>
    <value>[i] field:1:optional arguments</value>
    <value>[i] field:1:optional environment</value>
    <value>[i] field:0:optional workingDirectory</value>
    <value>[i] object:0:required inputRedirect</value>
    <value>[i] object:0:optional outputRedirect</value>
    <value>[i] object:0:optional errorRedirect</value>
    <value>[o] field:0:required exitValue</value>
    <value>[o] field:0:optional outputMessage</value>
    <value>[o] field:0:optional errorMessage</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNClN0cmluZyBjb21t
YW5kID0gbnVsbDsNCg0KUmVhZGVyIGlucHV0UmVhZGVyID0gbnVsbDsNCldyaXRlciBvdXRwdXRX
cml0ZXIgPSBudWxsOw0KV3JpdGVyIGVycm9yV3JpdGVyID0gbnVsbDsNCg0KaWYgKGN1cnNvci5m
aXJzdCgiY29tbWFuZCIpKQ0Kew0KICBjb21tYW5kID0gKFN0cmluZykgY3Vyc29yLmdldFZhbHVl
KCk7DQp9DQoNCmlmIChjb21tYW5kID09IG51bGwgfHwgY29tbWFuZC5sZW5ndGgoKSA9PSAwKQ0K
ew0KICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiTWlzc2luZyBpbnB1dCAnY29tbWFuZCci
KTsNCn0NCg0KaW5wdXRSZWFkZXIgPSBnZXRSZWFkZXIoY3Vyc29yLCAiaW5wdXRSZWRpcmVjdCIp
Ow0KDQpvdXRwdXRXcml0ZXIgPSBnZXRXcml0ZXIoY3Vyc29yLCAib3V0cHV0UmVkaXJlY3QiKTsN
CmVycm9yV3JpdGVyID0gZ2V0V3JpdGVyKGN1cnNvciwgImVycm9yUmVkaXJlY3QiKTsNCg0KU3Ry
aW5nW10gYXJncyA9IGN1cnNvci5maXJzdCgiYXJndW1lbnRzIikgPyAoU3RyaW5nW10pIGN1cnNv
ci5nZXRWYWx1ZSgpIDogbnVsbDsNClN0cmluZ1tdIGNtZEFyZ3MgPSBudWxsOw0KDQppZiAoYXJn
cyAhPSBudWxsICYmIGFyZ3MubGVuZ3RoID4gMCkNCnsNCiAgY21kQXJncyA9IG5ldyBTdHJpbmdb
YXJncy5sZW5ndGggKyAxXTsNCiAgY21kQXJnc1swXSA9IGNvbW1hbmQ7DQogIFN5c3RlbS5hcnJh
eWNvcHkoYXJncywgMCwgY21kQXJncywgMSwgYXJncy5sZW5ndGgpOw0KfQ0KDQpTdHJpbmdbXSBl
bnYgPSBjdXJzb3IuZmlyc3QoImVudmlyb25tZW50IikgPyAoU3RyaW5nW10pIGN1cnNvci5nZXRW
YWx1ZSgpIDogbnVsbDsNCkZpbGUgZm9sZGVyID0gY3Vyc29yLmZpcnN0KCJ3b3JraW5nRGlyZWN0
b3J5IikgPyBuZXcgRmlsZSgoU3RyaW5nKSBjdXJzb3IuZ2V0VmFsdWUoKSkgOiBudWxsOw0KDQpp
bnQgZXhpdFZhbHVlID0gOTk5Ow0KU3RyaW5nQnVmZmVyIG91dHB1dCA9IG5ldyBTdHJpbmdCdWZm
ZXIoKTsNClN0cmluZ0J1ZmZlciBlcnJvciA9IG5ldyBTdHJpbmdCdWZmZXIoKTsNCnRyeQ0Kew0K
ICBQcm9jZXNzIHByb2Nlc3M7DQogIGlmIChhcmdzID09IG51bGwgfHwgYXJncy5sZW5ndGggPT0g
MCkNCiAgew0KICAgIHByb2Nlc3MgPSBSdW50aW1lLmdldFJ1bnRpbWUoKS5leGVjKGNvbW1hbmQs
IGVudiwgZm9sZGVyKTsNCiAgfQ0KICBlbHNlDQogIHsNCiAgICBwcm9jZXNzID0gUnVudGltZS5n
ZXRSdW50aW1lKCkuZXhlYyhjbWRBcmdzLCBlbnYsIGZvbGRlcik7DQogIH0NCg0KICBTdHJlYW1D
b3BpZXIgbyA9IG5ldyBTdHJlYW1Db3BpZXIobmV3IEJ1ZmZlcmVkUmVhZGVyKG5ldyBJbnB1dFN0
cmVhbVJlYWRlcihwcm9jZXNzLmdldElucHV0U3RyZWFtKCkpKSwgb3V0cHV0V3JpdGVyKTsNCiAg
U3RyZWFtQ29waWVyIGUgPSBuZXcgU3RyZWFtQ29waWVyKG5ldyBCdWZmZXJlZFJlYWRlcihuZXcg
SW5wdXRTdHJlYW1SZWFkZXIocHJvY2Vzcy5nZXRFcnJvclN0cmVhbSgpKSksIGVycm9yV3JpdGVy
KTsNCiAgU3RyZWFtQ29waWVyIGkgPSBuZXcgU3RyZWFtQ29waWVyKGlucHV0UmVhZGVyLCBuZXcg
QnVmZmVyZWRXcml0ZXIobmV3IE91dHB1dFN0cmVhbVdyaXRlcihwcm9jZXNzLmdldE91dHB1dFN0
cmVhbSgpKSkpOw0KICBvLnN0YXJ0KCk7DQogIGUuc3RhcnQoKTsNCiAgaS5zdGFydCgpOw0KDQog
IGV4aXRWYWx1ZSA9IHByb2Nlc3Mud2FpdEZvcigpOw0KDQp9DQpjYXRjaCAoRXhjZXB0aW9uIGUp
DQp7DQogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUpOw0KfQ0KZmluYWxseQ0Kew0KICBJ
RGF0YVV0aWwucHV0KGN1cnNvciwgImV4aXRWYWx1ZSIsIFN0cmluZy52YWx1ZU9mKGV4aXRWYWx1
ZSkpOw0KICBpZiAob3V0cHV0V3JpdGVyIGluc3RhbmNlb2YgU3RyaW5nV3JpdGVyKQ0KICB7DQog
ICAgSURhdGFVdGlsLnB1dChjdXJzb3IsICJvdXRwdXRNZXNzYWdlIiwgKChTdHJpbmdXcml0ZXIp
IG91dHB1dFdyaXRlcikudG9TdHJpbmcoKSk7DQogIH0NCiAgaWYgKGVycm9yV3JpdGVyIGluc3Rh
bmNlb2YgU3RyaW5nV3JpdGVyKQ0KICB7DQogICAgSURhdGFVdGlsLnB1dChjdXJzb3IsICJlcnJv
ck1lc3NhZ2UiLCAoKFN0cmluZ1dyaXRlcikgZXJyb3JXcml0ZXIpLnRvU3RyaW5nKCkpOw0KICB9
DQogIGN1cnNvci5kZXN0cm95KCk7DQp9DQo=</value>
</Values>
